// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &blockedPageContentTypeResource{}
	_ resource.ResourceWithConfigure   = &blockedPageContentTypeResource{}
	_ resource.ResourceWithImportState = &blockedPageContentTypeResource{}
)

type blockedPageContentTypeResource struct{ client *clients.Client }

// NewBlockedPageContentTypeResource manages the BlockedPageContentType object (New-BlockedPageContentType / Get-BlockedPageContentType / Set-BlockedPageContentType / Remove-BlockedPageContentType).
func NewBlockedPageContentTypeResource() resource.Resource { return &blockedPageContentTypeResource{} }

type blockedPageContentTypeModel struct {
	ID          types.String `tfsdk:"id"`
	Identity    types.String `tfsdk:"identity"`
	ContentType types.String `tfsdk:"content_type"`
}

func (r *blockedPageContentTypeResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_blocked_page_content_type"
}

func (r *blockedPageContentTypeResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Blocks creation of pages of a content type (Set/Get/Remove-SPOBlockedPageCreationContentType, CSOM). Keyed by content type: StandardPage, WikiPage, FormPage, ClientSidePage.",
		Attributes: map[string]schema.Attribute{
			"id":           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":     schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"content_type": schema.StringAttribute{Optional: true, Computed: true, Description: "The blocked content type (echoes identity).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *blockedPageContentTypeResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *blockedPageContentTypeResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan blockedPageContentTypeModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := spo.NewSPOBlockedPageContentTypeParams{}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SPO.NewSPOBlockedPageContentType(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-BlockedPageContentType failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-BlockedPageContentType returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readBlockedPageContentType(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *blockedPageContentTypeResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state blockedPageContentTypeModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *blockedPageContentTypeResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state blockedPageContentTypeModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := spo.NewSPOBlockedPageContentTypeParams{}
	sp.Identity = id
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.NewSPOBlockedPageContentType(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-BlockedPageContentType failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *blockedPageContentTypeResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state blockedPageContentTypeModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.RemoveSPOBlockedPageContentType(ctx, spo.RemoveSPOBlockedPageContentTypeParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-BlockedPageContentType failed", err.Error())
		}
	}
}

func (r *blockedPageContentTypeResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *blockedPageContentTypeResource) identityOf(m blockedPageContentTypeModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *blockedPageContentTypeResource) refresh(ctx context.Context, identity string, m *blockedPageContentTypeModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SPO.GetSPOBlockedPageContentType(ctx, spo.GetSPOBlockedPageContentTypeParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-BlockedPageContentType failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readBlockedPageContentType(ctx, obj, m)
	return true
}

func readBlockedPageContentType(ctx context.Context, obj map[string]any, m *blockedPageContentTypeModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.ContentType = types.StringValue(getString(obj, "Id"))
	_ = ctx
}

func (r *blockedPageContentTypeResource) reconcileState(cfg, read *blockedPageContentTypeModel) {
	read.ContentType = reconcile.KeepStr(cfg.ContentType, read.ContentType)
}
