// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &hubSiteResource{}
	_ resource.ResourceWithConfigure   = &hubSiteResource{}
	_ resource.ResourceWithImportState = &hubSiteResource{}
)

type hubSiteResource struct{ client *clients.Client }

// NewHubSiteResource manages the HubSite object (New-HubSite / Get-HubSite / Set-HubSite / Remove-HubSite).
func NewHubSiteResource() resource.Resource { return &hubSiteResource{} }

type hubSiteModel struct {
	ID                   types.String `tfsdk:"id"`
	Identity             types.String `tfsdk:"identity"`
	Title                types.String `tfsdk:"title"`
	Description          types.String `tfsdk:"description"`
	LogoUrl              types.String `tfsdk:"logo_url"`
	RequiresJoinApproval types.Bool   `tfsdk:"requires_join_approval"`
	HubSiteId            types.String `tfsdk:"hub_site_id"`
}

func (r *hubSiteResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_hub_site"
}

func (r *hubSiteResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Registers an existing SharePoint site as a hub site and manages its hub settings (Register/Get/Set/Unregister-SPOHubSite, CSOM), keyed by the site URL.",
		Attributes: map[string]schema.Attribute{
			"id":                     schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":               schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"title":                  schema.StringAttribute{Optional: true, Computed: true, Description: "The hub site display name.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"description":            schema.StringAttribute{Optional: true, Computed: true, Description: "The hub site description.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"logo_url":               schema.StringAttribute{Optional: true, Computed: true, Description: "The hub site logo URL.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"requires_join_approval": schema.BoolAttribute{Optional: true, Computed: true, Description: "Whether joining the hub requires approval.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"hub_site_id":            schema.StringAttribute{Optional: true, Computed: true, Description: "The hub site GUID (server-assigned).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *hubSiteResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *hubSiteResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan hubSiteModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := spo.NewSPOHubSiteParams{
		Title:                plan.Title.ValueString(),
		Description:          plan.Description.ValueString(),
		LogoUrl:              plan.LogoUrl.ValueString(),
		RequiresJoinApproval: plan.RequiresJoinApproval.ValueBool(),
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SPO.NewSPOHubSite(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-HubSite failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-HubSite returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readHubSite(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *hubSiteResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state hubSiteModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *hubSiteResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state hubSiteModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := spo.SetSPOHubSiteParams{}
	sp.Identity = id
	sp.Title = plan.Title.ValueString()
	sp.Description = plan.Description.ValueString()
	sp.LogoUrl = plan.LogoUrl.ValueString()
	sp.RequiresJoinApproval = plan.RequiresJoinApproval.ValueBool()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPOHubSite(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-HubSite failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Title":       cfg.Title,
		"Description": cfg.Description,
		"LogoUrl":     cfg.LogoUrl,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *hubSiteResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state hubSiteModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.RemoveSPOHubSite(ctx, spo.RemoveSPOHubSiteParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-HubSite failed", err.Error())
		}
	}
}

func (r *hubSiteResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *hubSiteResource) identityOf(m hubSiteModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *hubSiteResource) refresh(ctx context.Context, identity string, m *hubSiteModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SPO.GetSPOHubSite(ctx, spo.GetSPOHubSiteParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-HubSite failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readHubSite(ctx, obj, m)
	return true
}

func readHubSite(ctx context.Context, obj map[string]any, m *hubSiteModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Title = types.StringValue(getString(obj, "Title"))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.LogoUrl = types.StringValue(getString(obj, "LogoUrl"))
	m.RequiresJoinApproval = types.BoolValue(getBool(obj, "RequiresJoinApproval"))
	m.HubSiteId = types.StringValue(getString(obj, "HubSiteId"))
	_ = ctx
}

func (r *hubSiteResource) reconcileState(cfg, read *hubSiteModel) {
	read.Title = reconcile.KeepStr(cfg.Title, read.Title)
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.LogoUrl = reconcile.KeepStr(cfg.LogoUrl, read.LogoUrl)
	read.RequiresJoinApproval = reconcile.KeepBool(cfg.RequiresJoinApproval, read.RequiresJoinApproval)
	read.HubSiteId = reconcile.KeepStr(cfg.HubSiteId, read.HubSiteId)
}
