// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &knowledgeHubSiteResource{}
	_ resource.ResourceWithConfigure   = &knowledgeHubSiteResource{}
	_ resource.ResourceWithImportState = &knowledgeHubSiteResource{}
)

type knowledgeHubSiteResource struct{ client *clients.Client }

// NewKnowledgeHubSiteResource manages the KnowledgeHubSite configuration (Get-KnowledgeHubSite / Set-KnowledgeHubSite); it adopts the existing object and is not deleted on destroy.
func NewKnowledgeHubSiteResource() resource.Resource { return &knowledgeHubSiteResource{} }

type knowledgeHubSiteModel struct {
	ID       types.String `tfsdk:"id"`
	Identity types.String `tfsdk:"identity"`
	Url      types.String `tfsdk:"url"`
}

func (r *knowledgeHubSiteResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_knowledge_hub_site"
}

func (r *knowledgeHubSiteResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the tenant knowledge hub site (Set/Get/Remove-SPOKnowledgeHubSite, CSOM). Singleton; not cleared on destroy.",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity": schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"url":      schema.StringAttribute{Required: true, Description: "The knowledge hub site URL."},
		},
	}
}

func (r *knowledgeHubSiteResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *knowledgeHubSiteResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan knowledgeHubSiteModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := spo.SetSPOKnowledgeHubSiteParams{}
	sp.Url = plan.Url.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPOKnowledgeHubSite(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-KnowledgeHubSite failed", err.Error())
		return
	}
	cfg := plan
	identity := ""
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *knowledgeHubSiteResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state knowledgeHubSiteModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *knowledgeHubSiteResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state knowledgeHubSiteModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := spo.SetSPOKnowledgeHubSiteParams{}
	sp.Url = plan.Url.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPOKnowledgeHubSite(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-KnowledgeHubSite failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Url": cfg.Url,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *knowledgeHubSiteResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("KnowledgeHubSite configuration not deleted", "This resource manages an existing KnowledgeHubSite configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *knowledgeHubSiteResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *knowledgeHubSiteResource) identityOf(m knowledgeHubSiteModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *knowledgeHubSiteResource) refresh(ctx context.Context, identity string, m *knowledgeHubSiteModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		_ = identity
		res, gerr := r.client.SPO.GetSPOKnowledgeHubSite(ctx, spo.GetSPOKnowledgeHubSiteParams{})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-KnowledgeHubSite failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readKnowledgeHubSite(ctx, obj, m)
	return true
}

func readKnowledgeHubSite(ctx context.Context, obj map[string]any, m *knowledgeHubSiteModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.Url = types.StringValue(getString(obj, "Url"))
	_ = ctx
}

func (r *knowledgeHubSiteResource) reconcileState(cfg, read *knowledgeHubSiteModel) {
	read.Url = reconcile.KeepStr(cfg.Url, read.Url)
}
