// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &knowledgeHubSiteDataSource{}
	_ datasource.DataSourceWithConfigure = &knowledgeHubSiteDataSource{}
)

type knowledgeHubSiteDataSource struct{ client *clients.Client }

// NewKnowledgeHubSiteDataSource looks up a KnowledgeHubSite object (Get-KnowledgeHubSite).
func NewKnowledgeHubSiteDataSource() datasource.DataSource { return &knowledgeHubSiteDataSource{} }

func (d *knowledgeHubSiteDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_knowledge_hub_site"
}

func (d *knowledgeHubSiteDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing KnowledgeHubSite object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity": schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"url":      schema.StringAttribute{Computed: true, Description: "The knowledge hub site URL."},
		},
	}
}

func (d *knowledgeHubSiteDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *knowledgeHubSiteDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data knowledgeHubSiteModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	get := func(ctx context.Context) (map[string]any, bool, error) {
		_ = identity
		res, gerr := d.client.SPO.GetSPOKnowledgeHubSite(ctx, spo.GetSPOKnowledgeHubSiteParams{})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-KnowledgeHubSite failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("KnowledgeHubSite not found", "no KnowledgeHubSite object for identity "+identity)
		return
	}
	readKnowledgeHubSite(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
