// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &listDesignResource{}
	_ resource.ResourceWithConfigure   = &listDesignResource{}
	_ resource.ResourceWithImportState = &listDesignResource{}
)

type listDesignResource struct{ client *clients.Client }

// NewListDesignResource manages the ListDesign object (New-ListDesign / Get-ListDesign / Set-ListDesign / Remove-ListDesign).
func NewListDesignResource() resource.Resource { return &listDesignResource{} }

type listDesignModel struct {
	ID          types.String `tfsdk:"id"`
	Identity    types.String `tfsdk:"identity"`
	Title       types.String `tfsdk:"title"`
	Description types.String `tfsdk:"description"`
	SiteScripts types.Set    `tfsdk:"site_scripts"`
}

func (r *listDesignResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_list_design"
}

func (r *listDesignResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a SharePoint list design (Add/Get/Remove-SPOListDesign, CSOM) — applies site scripts to a list. List designs are immutable: any change recreates the design.",
		Attributes: map[string]schema.Attribute{
			"id":           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":     schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"title":        schema.StringAttribute{Required: true, Description: "The list design display name.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"description":  schema.StringAttribute{Optional: true, Computed: true, Description: "The list design description.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"site_scripts": schema.SetAttribute{ElementType: types.StringType, Required: true, Description: "Ordered site-script GUIDs the design runs (at least one is required).", PlanModifiers: []planmodifier.Set{setplanmodifier.RequiresReplace()}},
		},
	}
}

func (r *listDesignResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *listDesignResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan listDesignModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := spo.NewSPOListDesignParams{
		Title:       plan.Title.ValueString(),
		Description: plan.Description.ValueString(),
		SiteScripts: toStringSlice(ctx, plan.SiteScripts, &resp.Diagnostics),
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SPO.NewSPOListDesign(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-ListDesign failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-ListDesign returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readListDesign(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *listDesignResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state listDesignModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *listDesignResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state listDesignModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := spo.SetSPOListDesignParams{}
	sp.Identity = id
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPOListDesign(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-ListDesign failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *listDesignResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state listDesignModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.RemoveSPOListDesign(ctx, spo.RemoveSPOListDesignParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-ListDesign failed", err.Error())
		}
	}
}

func (r *listDesignResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *listDesignResource) identityOf(m listDesignModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *listDesignResource) refresh(ctx context.Context, identity string, m *listDesignModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SPO.GetSPOListDesign(ctx, spo.GetSPOListDesignParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-ListDesign failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readListDesign(ctx, obj, m)
	return true
}

func readListDesign(ctx context.Context, obj map[string]any, m *listDesignModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.Title = types.StringValue(getString(obj, "Title"))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.SiteScripts = stringSetValue(ctx, getStringSlice(obj, "SiteScriptIds"))
	_ = ctx
}

func (r *listDesignResource) reconcileState(cfg, read *listDesignModel) {
	read.Title = reconcile.KeepStr(cfg.Title, read.Title)
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.SiteScripts = reconcile.KeepSet(cfg.SiteScripts, read.SiteScripts)
}
