// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &orgAssetsLibraryResource{}
	_ resource.ResourceWithConfigure   = &orgAssetsLibraryResource{}
	_ resource.ResourceWithImportState = &orgAssetsLibraryResource{}
)

type orgAssetsLibraryResource struct{ client *clients.Client }

// NewOrgAssetsLibraryResource manages the OrgAssetsLibrary object (New-OrgAssetsLibrary / Get-OrgAssetsLibrary / Set-OrgAssetsLibrary / Remove-OrgAssetsLibrary).
func NewOrgAssetsLibraryResource() resource.Resource { return &orgAssetsLibraryResource{} }

type orgAssetsLibraryModel struct {
	ID           types.String `tfsdk:"id"`
	Identity     types.String `tfsdk:"identity"`
	OrgAssetType types.String `tfsdk:"org_asset_type"`
	ThumbnailUrl types.String `tfsdk:"thumbnail_url"`
	CdnType      types.String `tfsdk:"cdn_type"`
}

func (r *orgAssetsLibraryResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_org_assets_library"
}

func (r *orgAssetsLibraryResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Registers a document library as an organization assets library (Add/Get/Set/Remove-SPOOrgAssetsLibrary, CSOM), keyed by the library URL. Surfaces its images/templates/fonts to the org.",
		Attributes: map[string]schema.Attribute{
			"id":             schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":       schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"org_asset_type": schema.StringAttribute{Required: true, Description: "Asset type: ImageDocumentLibrary, OfficeTemplateLibrary or OfficeFontLibrary."},
			"thumbnail_url":  schema.StringAttribute{Optional: true, Computed: true, Description: "Optional thumbnail image URL for the library.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"cdn_type":       schema.StringAttribute{Optional: true, Computed: true, Description: "CDN the library is served from: Public or Private (default Private). Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *orgAssetsLibraryResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *orgAssetsLibraryResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan orgAssetsLibraryModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := spo.NewSPOOrgAssetsLibraryParams{
		OrgAssetType: plan.OrgAssetType.ValueString(),
		ThumbnailUrl: plan.ThumbnailUrl.ValueString(),
		CdnType:      plan.CdnType.ValueString(),
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SPO.NewSPOOrgAssetsLibrary(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-OrgAssetsLibrary failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-OrgAssetsLibrary returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readOrgAssetsLibrary(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *orgAssetsLibraryResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state orgAssetsLibraryModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *orgAssetsLibraryResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state orgAssetsLibraryModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := spo.SetSPOOrgAssetsLibraryParams{}
	sp.Identity = id
	sp.OrgAssetType = plan.OrgAssetType.ValueString()
	sp.ThumbnailUrl = plan.ThumbnailUrl.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPOOrgAssetsLibrary(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-OrgAssetsLibrary failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"OrgAssetType": cfg.OrgAssetType,
		"ThumbnailUrl": cfg.ThumbnailUrl,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *orgAssetsLibraryResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state orgAssetsLibraryModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.RemoveSPOOrgAssetsLibrary(ctx, spo.RemoveSPOOrgAssetsLibraryParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-OrgAssetsLibrary failed", err.Error())
		}
	}
}

func (r *orgAssetsLibraryResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *orgAssetsLibraryResource) identityOf(m orgAssetsLibraryModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *orgAssetsLibraryResource) refresh(ctx context.Context, identity string, m *orgAssetsLibraryModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SPO.GetSPOOrgAssetsLibrary(ctx, spo.GetSPOOrgAssetsLibraryParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-OrgAssetsLibrary failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readOrgAssetsLibrary(ctx, obj, m)
	return true
}

func readOrgAssetsLibrary(ctx context.Context, obj map[string]any, m *orgAssetsLibraryModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.OrgAssetType = types.StringValue(getString(obj, "OrgAssetType"))
	m.ThumbnailUrl = types.StringValue(getString(obj, "ThumbnailUrl"))
	m.CdnType = types.StringValue(getString(obj, "CdnType"))
	_ = ctx
}

func (r *orgAssetsLibraryResource) reconcileState(cfg, read *orgAssetsLibraryModel) {
	read.OrgAssetType = reconcile.KeepStr(cfg.OrgAssetType, read.OrgAssetType)
	read.ThumbnailUrl = reconcile.KeepStr(cfg.ThumbnailUrl, read.ThumbnailUrl)
	read.CdnType = reconcile.KeepStr(cfg.CdnType, read.CdnType)
}
