// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &orgAssetsLibraryDataSource{}
	_ datasource.DataSourceWithConfigure = &orgAssetsLibraryDataSource{}
)

type orgAssetsLibraryDataSource struct{ client *clients.Client }

// NewOrgAssetsLibraryDataSource looks up a OrgAssetsLibrary object (Get-OrgAssetsLibrary).
func NewOrgAssetsLibraryDataSource() datasource.DataSource { return &orgAssetsLibraryDataSource{} }

func (d *orgAssetsLibraryDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_org_assets_library"
}

func (d *orgAssetsLibraryDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing OrgAssetsLibrary object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":             schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":       schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"org_asset_type": schema.StringAttribute{Computed: true, Description: "Asset type: ImageDocumentLibrary, OfficeTemplateLibrary or OfficeFontLibrary."},
			"thumbnail_url":  schema.StringAttribute{Computed: true, Description: "Optional thumbnail image URL for the library."},
			"cdn_type":       schema.StringAttribute{Computed: true, Description: "CDN the library is served from: Public or Private (default Private). Changing it forces replacement."},
		},
	}
}

func (d *orgAssetsLibraryDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *orgAssetsLibraryDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data orgAssetsLibraryModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SPO.GetSPOOrgAssetsLibrary(ctx, spo.GetSPOOrgAssetsLibraryParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-OrgAssetsLibrary failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("OrgAssetsLibrary not found", "no OrgAssetsLibrary object for identity "+identity)
		return
	}
	readOrgAssetsLibrary(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
