// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &restrictedSearchResource{}
	_ resource.ResourceWithConfigure   = &restrictedSearchResource{}
	_ resource.ResourceWithImportState = &restrictedSearchResource{}
)

type restrictedSearchResource struct{ client *clients.Client }

// NewRestrictedSearchResource manages the RestrictedSearch configuration (Get-RestrictedSearch / Set-RestrictedSearch); it adopts the existing object and is not deleted on destroy.
func NewRestrictedSearchResource() resource.Resource { return &restrictedSearchResource{} }

type restrictedSearchModel struct {
	ID          types.String `tfsdk:"id"`
	Identity    types.String `tfsdk:"identity"`
	Mode        types.String `tfsdk:"mode"`
	AllowedList types.Set    `tfsdk:"allowed_list"`
}

func (r *restrictedSearchResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_restricted_search"
}

func (r *restrictedSearchResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages tenant restricted search (mode + allowed site list; Set/Get-SPORestrictedSearchMode + Add/Remove-SPORestrictedSearchAllowedList, CSOM). Singleton. Requires a SharePoint Premium license.",
		Attributes: map[string]schema.Attribute{
			"id":           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":     schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"mode":         schema.StringAttribute{Required: true, Description: "Restricted search mode: Disabled or Enabled."},
			"allowed_list": schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Site URLs allowed in search when restricted.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *restrictedSearchResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *restrictedSearchResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan restrictedSearchModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := spo.SetSPORestrictedSearchParams{}
	sp.Mode = plan.Mode.ValueString()
	sp.AllowedList = toStringSlice(ctx, plan.AllowedList, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPORestrictedSearch(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-RestrictedSearch failed", err.Error())
		return
	}
	cfg := plan
	identity := ""
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *restrictedSearchResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state restrictedSearchModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *restrictedSearchResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state restrictedSearchModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := spo.SetSPORestrictedSearchParams{}
	sp.Mode = plan.Mode.ValueString()
	sp.AllowedList = toStringSlice(ctx, plan.AllowedList, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPORestrictedSearch(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-RestrictedSearch failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Mode": cfg.Mode,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *restrictedSearchResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("RestrictedSearch configuration not deleted", "This resource manages an existing RestrictedSearch configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *restrictedSearchResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *restrictedSearchResource) identityOf(m restrictedSearchModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *restrictedSearchResource) refresh(ctx context.Context, identity string, m *restrictedSearchModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		_ = identity
		res, gerr := r.client.SPO.GetSPORestrictedSearch(ctx, spo.GetSPORestrictedSearchParams{})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-RestrictedSearch failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readRestrictedSearch(ctx, obj, m)
	return true
}

func readRestrictedSearch(ctx context.Context, obj map[string]any, m *restrictedSearchModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.Mode = types.StringValue(getString(obj, "Mode"))
	m.AllowedList = stringSetValue(ctx, getStringSlice(obj, "AllowedList"))
	_ = ctx
}

func (r *restrictedSearchResource) reconcileState(cfg, read *restrictedSearchModel) {
	read.Mode = reconcile.KeepStr(cfg.Mode, read.Mode)
	read.AllowedList = reconcile.KeepSet(cfg.AllowedList, read.AllowedList)
}
