// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &siteDesignDataSource{}
	_ datasource.DataSourceWithConfigure = &siteDesignDataSource{}
)

type siteDesignDataSource struct{ client *clients.Client }

// NewSiteDesignDataSource looks up a SiteDesign object (Get-SiteDesign).
func NewSiteDesignDataSource() datasource.DataSource { return &siteDesignDataSource{} }

func (d *siteDesignDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_site_design"
}

func (d *siteDesignDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing SiteDesign object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                     schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":               schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"title":                  schema.StringAttribute{Computed: true, Description: "The site design display name."},
			"web_template":           schema.StringAttribute{Computed: true, Description: "Site template the design applies to: 64 (team site), 68 (communication site), 1 (group)."},
			"site_scripts":           schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Ordered site-script GUIDs the design runs."},
			"description":            schema.StringAttribute{Computed: true, Description: "The site design description."},
			"preview_image_url":      schema.StringAttribute{Computed: true, Description: "Preview image URL."},
			"preview_image_alt_text": schema.StringAttribute{Computed: true, Description: "Preview image alt text."},
			"is_default":             schema.BoolAttribute{Computed: true, Description: "Whether the design applies to all new sites of the web template."},
		},
	}
}

func (d *siteDesignDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *siteDesignDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data siteDesignModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SPO.GetSPOSiteDesign(ctx, spo.GetSPOSiteDesignParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-SiteDesign failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("SiteDesign not found", "no SiteDesign object for identity "+identity)
		return
	}
	readSiteDesign(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
