// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &siteDesignRightsResource{}
	_ resource.ResourceWithConfigure   = &siteDesignRightsResource{}
	_ resource.ResourceWithImportState = &siteDesignRightsResource{}
)

type siteDesignRightsResource struct{ client *clients.Client }

// NewSiteDesignRightsResource manages the SiteDesignRights object (New-SiteDesignRights / Get-SiteDesignRights / Set-SiteDesignRights / Remove-SiteDesignRights).
func NewSiteDesignRightsResource() resource.Resource { return &siteDesignRightsResource{} }

type siteDesignRightsModel struct {
	ID         types.String `tfsdk:"id"`
	Identity   types.String `tfsdk:"identity"`
	Principals types.Set    `tfsdk:"principals"`
}

func (r *siteDesignRightsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_site_design_rights"
}

func (r *siteDesignRightsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Grants View rights on a site design to principals (Grant/Revoke/Get-SPOSiteDesignRights, CSOM), keyed by the site design GUID.",
		Attributes: map[string]schema.Attribute{
			"id":         schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":   schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"principals": schema.SetAttribute{ElementType: types.StringType, Required: true, Description: "User/group principal names granted View rights on the design."},
		},
	}
}

func (r *siteDesignRightsResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *siteDesignRightsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan siteDesignRightsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := spo.NewSPOSiteDesignRightsParams{
		Principals: toStringSlice(ctx, plan.Principals, &resp.Diagnostics),
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SPO.NewSPOSiteDesignRights(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-SiteDesignRights failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-SiteDesignRights returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readSiteDesignRights(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *siteDesignRightsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state siteDesignRightsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *siteDesignRightsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state siteDesignRightsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := spo.SetSPOSiteDesignRightsParams{}
	sp.Identity = id
	sp.Principals = toStringSlice(ctx, plan.Principals, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPOSiteDesignRights(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-SiteDesignRights failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *siteDesignRightsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state siteDesignRightsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.RemoveSPOSiteDesignRights(ctx, spo.RemoveSPOSiteDesignRightsParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-SiteDesignRights failed", err.Error())
		}
	}
}

func (r *siteDesignRightsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *siteDesignRightsResource) identityOf(m siteDesignRightsModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *siteDesignRightsResource) refresh(ctx context.Context, identity string, m *siteDesignRightsModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SPO.GetSPOSiteDesignRights(ctx, spo.GetSPOSiteDesignRightsParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-SiteDesignRights failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readSiteDesignRights(ctx, obj, m)
	return true
}

func readSiteDesignRights(ctx context.Context, obj map[string]any, m *siteDesignRightsModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Principals = stringSetValue(ctx, getStringSlice(obj, "Principals"))
	_ = ctx
}

func (r *siteDesignRightsResource) reconcileState(cfg, read *siteDesignRightsModel) {
	read.Principals = reconcile.KeepSet(cfg.Principals, read.Principals)
}
