// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &siteDesignResource{}
	_ resource.ResourceWithConfigure   = &siteDesignResource{}
	_ resource.ResourceWithImportState = &siteDesignResource{}
)

type siteDesignResource struct{ client *clients.Client }

// NewSiteDesignResource manages the SiteDesign object (New-SiteDesign / Get-SiteDesign / Set-SiteDesign / Remove-SiteDesign).
func NewSiteDesignResource() resource.Resource { return &siteDesignResource{} }

type siteDesignModel struct {
	ID                  types.String `tfsdk:"id"`
	Identity            types.String `tfsdk:"identity"`
	Title               types.String `tfsdk:"title"`
	WebTemplate         types.String `tfsdk:"web_template"`
	SiteScripts         types.Set    `tfsdk:"site_scripts"`
	Description         types.String `tfsdk:"description"`
	PreviewImageUrl     types.String `tfsdk:"preview_image_url"`
	PreviewImageAltText types.String `tfsdk:"preview_image_alt_text"`
	IsDefault           types.Bool   `tfsdk:"is_default"`
}

func (r *siteDesignResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_site_design"
}

func (r *siteDesignResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a SharePoint site design (Add/Get/Set/Remove-SPOSiteDesign, CSOM) — applies one or more site scripts when a site is created or the design is invoked.",
		Attributes: map[string]schema.Attribute{
			"id":                     schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":               schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"title":                  schema.StringAttribute{Required: true, Description: "The site design display name."},
			"web_template":           schema.StringAttribute{Required: true, Description: "Site template the design applies to: 64 (team site), 68 (communication site), 1 (group)."},
			"site_scripts":           schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Ordered site-script GUIDs the design runs.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"description":            schema.StringAttribute{Optional: true, Computed: true, Description: "The site design description.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"preview_image_url":      schema.StringAttribute{Optional: true, Computed: true, Description: "Preview image URL.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"preview_image_alt_text": schema.StringAttribute{Optional: true, Computed: true, Description: "Preview image alt text.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"is_default":             schema.BoolAttribute{Optional: true, Computed: true, Description: "Whether the design applies to all new sites of the web template.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *siteDesignResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *siteDesignResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan siteDesignModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := spo.NewSPOSiteDesignParams{
		Title:               plan.Title.ValueString(),
		WebTemplate:         plan.WebTemplate.ValueString(),
		SiteScripts:         toStringSlice(ctx, plan.SiteScripts, &resp.Diagnostics),
		Description:         plan.Description.ValueString(),
		PreviewImageUrl:     plan.PreviewImageUrl.ValueString(),
		PreviewImageAltText: plan.PreviewImageAltText.ValueString(),
		IsDefault:           plan.IsDefault.ValueBool(),
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SPO.NewSPOSiteDesign(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-SiteDesign failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-SiteDesign returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readSiteDesign(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *siteDesignResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state siteDesignModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *siteDesignResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state siteDesignModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := spo.SetSPOSiteDesignParams{}
	sp.Identity = id
	sp.Title = plan.Title.ValueString()
	sp.WebTemplate = plan.WebTemplate.ValueString()
	sp.SiteScripts = toStringSlice(ctx, plan.SiteScripts, &resp.Diagnostics)
	sp.Description = plan.Description.ValueString()
	sp.PreviewImageUrl = plan.PreviewImageUrl.ValueString()
	sp.PreviewImageAltText = plan.PreviewImageAltText.ValueString()
	sp.IsDefault = plan.IsDefault.ValueBool()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPOSiteDesign(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-SiteDesign failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Title":               cfg.Title,
		"WebTemplate":         cfg.WebTemplate,
		"Description":         cfg.Description,
		"PreviewImageUrl":     cfg.PreviewImageUrl,
		"PreviewImageAltText": cfg.PreviewImageAltText,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *siteDesignResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state siteDesignModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.RemoveSPOSiteDesign(ctx, spo.RemoveSPOSiteDesignParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-SiteDesign failed", err.Error())
		}
	}
}

func (r *siteDesignResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *siteDesignResource) identityOf(m siteDesignModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *siteDesignResource) refresh(ctx context.Context, identity string, m *siteDesignModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SPO.GetSPOSiteDesign(ctx, spo.GetSPOSiteDesignParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-SiteDesign failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readSiteDesign(ctx, obj, m)
	return true
}

func readSiteDesign(ctx context.Context, obj map[string]any, m *siteDesignModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.Title = types.StringValue(getString(obj, "Title"))
	m.WebTemplate = types.StringValue(getString(obj, "WebTemplate"))
	m.SiteScripts = stringSetValue(ctx, getStringSlice(obj, "SiteScriptIds"))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.PreviewImageUrl = types.StringValue(getString(obj, "PreviewImageUrl"))
	m.PreviewImageAltText = types.StringValue(getString(obj, "PreviewImageAltText"))
	m.IsDefault = types.BoolValue(getBool(obj, "IsDefault"))
	_ = ctx
}

func (r *siteDesignResource) reconcileState(cfg, read *siteDesignModel) {
	read.Title = reconcile.KeepStr(cfg.Title, read.Title)
	read.WebTemplate = reconcile.KeepStr(cfg.WebTemplate, read.WebTemplate)
	read.SiteScripts = reconcile.KeepSet(cfg.SiteScripts, read.SiteScripts)
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.PreviewImageUrl = reconcile.KeepStr(cfg.PreviewImageUrl, read.PreviewImageUrl)
	read.PreviewImageAltText = reconcile.KeepStr(cfg.PreviewImageAltText, read.PreviewImageAltText)
	read.IsDefault = reconcile.KeepBool(cfg.IsDefault, read.IsDefault)
}
