// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &siteScriptResource{}
	_ resource.ResourceWithConfigure   = &siteScriptResource{}
	_ resource.ResourceWithImportState = &siteScriptResource{}
)

type siteScriptResource struct{ client *clients.Client }

// NewSiteScriptResource manages the SiteScript object (New-SiteScript / Get-SiteScript / Set-SiteScript / Remove-SiteScript).
func NewSiteScriptResource() resource.Resource { return &siteScriptResource{} }

type siteScriptModel struct {
	ID          types.String `tfsdk:"id"`
	Identity    types.String `tfsdk:"identity"`
	Title       types.String `tfsdk:"title"`
	Description types.String `tfsdk:"description"`
	Content     types.String `tfsdk:"content"`
}

func (r *siteScriptResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_site_script"
}

func (r *siteScriptResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a SharePoint site script (Add/Get/Set/Remove-SPOSiteScript, CSOM) — a JSON document consumed by site designs.",
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":    schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"title":       schema.StringAttribute{Required: true, Description: "The site script display name."},
			"description": schema.StringAttribute{Optional: true, Computed: true, Description: "The site script description.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"content":     schema.StringAttribute{Required: true, Description: "The site script JSON (the actions document)."},
		},
	}
}

func (r *siteScriptResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *siteScriptResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan siteScriptModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := spo.NewSPOSiteScriptParams{
		Title:       plan.Title.ValueString(),
		Description: plan.Description.ValueString(),
		Content:     plan.Content.ValueString(),
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SPO.NewSPOSiteScript(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-SiteScript failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-SiteScript returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readSiteScript(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *siteScriptResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state siteScriptModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *siteScriptResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state siteScriptModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := spo.SetSPOSiteScriptParams{}
	sp.Identity = id
	sp.Title = plan.Title.ValueString()
	sp.Description = plan.Description.ValueString()
	sp.Content = plan.Content.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPOSiteScript(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-SiteScript failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Title":       cfg.Title,
		"Description": cfg.Description,
		"Content":     cfg.Content,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *siteScriptResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state siteScriptModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.RemoveSPOSiteScript(ctx, spo.RemoveSPOSiteScriptParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-SiteScript failed", err.Error())
		}
	}
}

func (r *siteScriptResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *siteScriptResource) identityOf(m siteScriptModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *siteScriptResource) refresh(ctx context.Context, identity string, m *siteScriptModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SPO.GetSPOSiteScript(ctx, spo.GetSPOSiteScriptParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-SiteScript failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readSiteScript(ctx, obj, m)
	return true
}

func readSiteScript(ctx context.Context, obj map[string]any, m *siteScriptModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.Title = types.StringValue(getString(obj, "Title"))
	m.Description = types.StringValue(getString(obj, "Description"))
	_ = ctx
}

func (r *siteScriptResource) reconcileState(cfg, read *siteScriptModel) {
	read.Title = reconcile.KeepStr(cfg.Title, read.Title)
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.Content = reconcile.KeepStr(cfg.Content, read.Content)
}
