// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &siteResource{}
	_ resource.ResourceWithConfigure   = &siteResource{}
	_ resource.ResourceWithImportState = &siteResource{}
)

type siteResource struct{ client *clients.Client }

// NewSiteResource manages the Site configuration (Get-Site / Set-Site); it adopts the existing object and is not deleted on destroy.
func NewSiteResource() resource.Resource { return &siteResource{} }

type siteModel struct {
	ID                                                             types.String `tfsdk:"id"`
	Identity                                                       types.String `tfsdk:"identity"`
	AllowDownloadingNonWebViewableFiles                            types.Bool   `tfsdk:"allow_downloading_non_web_viewable_files"`
	AllowEditing                                                   types.Bool   `tfsdk:"allow_editing"`
	AllowFileArchive                                               types.Bool   `tfsdk:"allow_file_archive"`
	AllowSelfServiceUpgrade                                        types.Bool   `tfsdk:"allow_self_service_upgrade"`
	AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled types.Bool   `tfsdk:"allow_web_property_bag_update_when_deny_add_and_customize_pages_is_enabled"`
	AnonymousLinkExpirationInDays                                  types.Int64  `tfsdk:"anonymous_link_expiration_in_days"`
	ApplyToExistingDocumentLibraries                               types.Bool   `tfsdk:"apply_to_existing_document_libraries"`
	ApplyToNewDocumentLibraries                                    types.Bool   `tfsdk:"apply_to_new_document_libraries"`
	AuthenticationContextName                                      types.String `tfsdk:"authentication_context_name"`
	BlockDownloadLinksFileType                                     types.String `tfsdk:"block_download_links_file_type"`
	BlockDownloadPolicy                                            types.Bool   `tfsdk:"block_download_policy"`
	BlockGuestsAsSiteAdmin                                         types.String `tfsdk:"block_guests_as_site_admin"`
	ClearGroupId                                                   types.Bool   `tfsdk:"clear_group_id"`
	ClearRestrictedAccessControl                                   types.Bool   `tfsdk:"clear_restricted_access_control"`
	CommentsOnSitePagesDisabled                                    types.Bool   `tfsdk:"comments_on_site_pages_disabled"`
	ConditionalAccessPolicy                                        types.String `tfsdk:"conditional_access_policy"`
	DefaultLinkPermission                                          types.String `tfsdk:"default_link_permission"`
	DefaultLinkToExistingAccess                                    types.Bool   `tfsdk:"default_link_to_existing_access"`
	DefaultLinkToExistingAccessReset                               types.Bool   `tfsdk:"default_link_to_existing_access_reset"`
	DefaultMainLinkScope                                           types.String `tfsdk:"default_main_link_scope"`
	DefaultShareLinkRole                                           types.String `tfsdk:"default_share_link_role"`
	DefaultShareLinkScope                                          types.String `tfsdk:"default_share_link_scope"`
	DefaultSharingLinkType                                         types.String `tfsdk:"default_sharing_link_type"`
	DenyAddAndCustomizePages                                       types.String `tfsdk:"deny_add_and_customize_pages"`
	DisableAppViews                                                types.String `tfsdk:"disable_app_views"`
	DisableClassicPageBaselineSecurityMode                         types.Bool   `tfsdk:"disable_classic_page_baseline_security_mode"`
	DisableCompanyWideSharingLinks                                 types.String `tfsdk:"disable_company_wide_sharing_links"`
	DisableFlows                                                   types.String `tfsdk:"disable_flows"`
	DisableSiteBranding                                            types.Bool   `tfsdk:"disable_site_branding"`
	EnableAutoExpirationVersionTrim                                types.Bool   `tfsdk:"enable_auto_expiration_version_trim"`
	ExcludeBlockDownloadPolicySiteOwners                           types.Bool   `tfsdk:"exclude_block_download_policy_site_owners"`
	ExcludeBlockDownloadSharePointGroups                           types.Set    `tfsdk:"exclude_block_download_share_point_groups"`
	ExcludedBlockDownloadGroupIds                                  types.Set    `tfsdk:"excluded_block_download_group_ids"`
	ExpireVersionsAfterDays                                        types.Int64  `tfsdk:"expire_versions_after_days"`
	ExternalUserExpirationInDays                                   types.Int64  `tfsdk:"external_user_expiration_in_days"`
	FileTypesForVersionExpiration                                  types.Set    `tfsdk:"file_types_for_version_expiration"`
	HidePeoplePreviewingFiles                                      types.Bool   `tfsdk:"hide_people_previewing_files"`
	HidePeopleWhoHaveListsOpen                                     types.Bool   `tfsdk:"hide_people_who_have_lists_open"`
	InheritVersionPolicyFromTenant                                 types.Bool   `tfsdk:"inherit_version_policy_from_tenant"`
	IsAuthoritative                                                types.Bool   `tfsdk:"is_authoritative"`
	LimitedAccessFileType                                          types.String `tfsdk:"limited_access_file_type"`
	ListsShowHeaderAndNavigation                                   types.Bool   `tfsdk:"lists_show_header_and_navigation"`
	LockState                                                      types.String `tfsdk:"lock_state"`
	LoopDefaultSharingLinkRole                                     types.String `tfsdk:"loop_default_sharing_link_role"`
	LoopDefaultSharingLinkScope                                    types.String `tfsdk:"loop_default_sharing_link_scope"`
	MajorVersionLimit                                              types.Int64  `tfsdk:"major_version_limit"`
	MajorWithMinorVersionsLimit                                    types.Int64  `tfsdk:"major_with_minor_versions_limit"`
	MediaTranscription                                             types.String `tfsdk:"media_transcription"`
	OverrideBlockUserInfoVisibility                                types.String `tfsdk:"override_block_user_info_visibility"`
	OverrideSharingCapability                                      types.Bool   `tfsdk:"override_sharing_capability"`
	OverrideTenantAnonymousLinkExpirationPolicy                    types.Bool   `tfsdk:"override_tenant_anonymous_link_expiration_policy"`
	OverrideTenantExternalUserExpirationPolicy                     types.Bool   `tfsdk:"override_tenant_external_user_expiration_policy"`
	Owner                                                          types.String `tfsdk:"owner"`
	ReadOnlyForBlockDownloadPolicy                                 types.Bool   `tfsdk:"read_only_for_block_download_policy"`
	ReadOnlyForUnmanagedDevices                                    types.Bool   `tfsdk:"read_only_for_unmanaged_devices"`
	RemoveVersionExpirationFileTypeOverride                        types.Set    `tfsdk:"remove_version_expiration_file_type_override"`
	RequestFilesLinkEnabled                                        types.Bool   `tfsdk:"request_files_link_enabled"`
	RequestFilesLinkExpirationInDays                               types.Int64  `tfsdk:"request_files_link_expiration_in_days"`
	RestrictContentOrgWideSearch                                   types.Bool   `tfsdk:"restrict_content_org_wide_search"`
	RestrictedAccessControl                                        types.Bool   `tfsdk:"restricted_access_control"`
	RestrictedAccessControlGroups                                  types.Set    `tfsdk:"restricted_access_control_groups"`
	RestrictedContentDiscoveryforCopilotAndAgents                  types.Bool   `tfsdk:"restricted_content_discoveryfor_copilot_and_agents"`
	SandboxedCodeActivationCapability                              types.String `tfsdk:"sandboxed_code_activation_capability"`
	SensitivityLabel                                               types.String `tfsdk:"sensitivity_label"`
	SharingAllowedDomainList                                       types.String `tfsdk:"sharing_allowed_domain_list"`
	SharingBlockedDomainList                                       types.String `tfsdk:"sharing_blocked_domain_list"`
	SharingCapability                                              types.String `tfsdk:"sharing_capability"`
	SharingDomainRestrictionMode                                   types.String `tfsdk:"sharing_domain_restriction_mode"`
	ShowPeoplePickerSuggestionsForGuestUsers                       types.Bool   `tfsdk:"show_people_picker_suggestions_for_guest_users"`
	SocialBarOnSitePagesDisabled                                   types.Bool   `tfsdk:"social_bar_on_site_pages_disabled"`
	Title                                                          types.String `tfsdk:"title"`
}

func (r *siteResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_site"
}

func (r *siteResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the admin settings of an existing SharePoint Online site collection via Get-/Set-SPOSite (CSOM), keyed by the site URL (identity). It adopts an existing site and is not deleted on destroy (it does not create or remove the site collection itself).",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity": schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"allow_downloading_non_web_viewable_files": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM AllowDownloadingNonWebViewableFiles property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_editing":              schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM AllowEditing property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_file_archive":         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM AllowFileArchive property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_self_service_upgrade": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM AllowSelfServiceUpgrade property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"allow_web_property_bag_update_when_deny_add_and_customize_pages_is_enabled": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"anonymous_link_expiration_in_days":                                          schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the CSOM AnonymousLinkExpirationInDays property.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"apply_to_existing_document_libraries":                                       schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM ApplyToExistingDocumentLibraries property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"apply_to_new_document_libraries":                                            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM ApplyToNewDocumentLibraries property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"authentication_context_name":                                                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM AuthenticationContextName property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"block_download_links_file_type":                                             schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM BlockDownloadLinksFileType property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"block_download_policy":                                                      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM BlockDownloadPolicy property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"block_guests_as_site_admin":                                                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM BlockGuestsAsSiteAdmin property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"clear_group_id":                                                             schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM ClearGroupId property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"clear_restricted_access_control":                                            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM ClearRestrictedAccessControl property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"comments_on_site_pages_disabled":                                            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM CommentsOnSitePagesDisabled property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"conditional_access_policy":                                                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM ConditionalAccessPolicy property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"default_link_permission":                                                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM DefaultLinkPermission property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"default_link_to_existing_access":                                            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM DefaultLinkToExistingAccess property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"default_link_to_existing_access_reset":                                      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM DefaultLinkToExistingAccessReset property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"default_main_link_scope":                                                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM DefaultMainLinkScope property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"default_share_link_role":                                                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM DefaultShareLinkRole property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"default_share_link_scope":                                                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM DefaultShareLinkScope property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"default_sharing_link_type":                                                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM DefaultSharingLinkType property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"deny_add_and_customize_pages":                                               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM DenyAddAndCustomizePages property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"disable_app_views":                                                          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM DisableAppViews property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"disable_classic_page_baseline_security_mode":                                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM DisableClassicPageBaselineSecurityMode property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"disable_company_wide_sharing_links":                                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM DisableCompanyWideSharingLinks property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"disable_flows":                                                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM DisableFlows property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"disable_site_branding":                                                      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM DisableSiteBranding property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"enable_auto_expiration_version_trim":                                        schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM EnableAutoExpirationVersionTrim property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"exclude_block_download_policy_site_owners":                                  schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM ExcludeBlockDownloadPolicySiteOwners property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"exclude_block_download_share_point_groups":                                  schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the CSOM ExcludeBlockDownloadSharePointGroups property.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"excluded_block_download_group_ids":                                          schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the CSOM ExcludedBlockDownloadGroupIds property.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"expire_versions_after_days":                                                 schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the CSOM ExpireVersionsAfterDays property.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"external_user_expiration_in_days":                                           schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the CSOM ExternalUserExpirationInDays property.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"file_types_for_version_expiration":                                          schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the CSOM FileTypesForVersionExpiration property.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"hide_people_previewing_files":                                               schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM HidePeoplePreviewingFiles property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"hide_people_who_have_lists_open":                                            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM HidePeopleWhoHaveListsOpen property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"inherit_version_policy_from_tenant":                                         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM InheritVersionPolicyFromTenant property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"is_authoritative":                                                           schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM IsAuthoritative property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"limited_access_file_type":                                                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM LimitedAccessFileType property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"lists_show_header_and_navigation":                                           schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM ListsShowHeaderAndNavigation property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"lock_state":                                                                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM LockState property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"loop_default_sharing_link_role":                                             schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM LoopDefaultSharingLinkRole property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"loop_default_sharing_link_scope":                                            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM LoopDefaultSharingLinkScope property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"major_version_limit":                                                        schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the CSOM MajorVersionLimit property.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"major_with_minor_versions_limit":                                            schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the CSOM MajorWithMinorVersionsLimit property.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"media_transcription":                                                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM MediaTranscription property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"override_block_user_info_visibility":                                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM OverrideBlockUserInfoVisibility property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"override_sharing_capability":                                                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM OverrideSharingCapability property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"override_tenant_anonymous_link_expiration_policy":                           schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM OverrideTenantAnonymousLinkExpirationPolicy property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"override_tenant_external_user_expiration_policy":                            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM OverrideTenantExternalUserExpirationPolicy property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"owner":                                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM Owner property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"read_only_for_block_download_policy":                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM ReadOnlyForBlockDownloadPolicy property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"read_only_for_unmanaged_devices":                    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM ReadOnlyForUnmanagedDevices property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"remove_version_expiration_file_type_override":       schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the CSOM RemoveVersionExpirationFileTypeOverride property.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"request_files_link_enabled":                         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM RequestFilesLinkEnabled property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"request_files_link_expiration_in_days":              schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the CSOM RequestFilesLinkExpirationInDays property.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"restrict_content_org_wide_search":                   schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM RestrictContentOrgWideSearch property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"restricted_access_control":                          schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM RestrictedAccessControl property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"restricted_access_control_groups":                   schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the CSOM RestrictedAccessControlGroups property.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"restricted_content_discoveryfor_copilot_and_agents": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM RestrictedContentDiscoveryforCopilotAndAgents property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"sandboxed_code_activation_capability":               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM SandboxedCodeActivationCapability property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"sensitivity_label":                                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM SensitivityLabel property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"sharing_allowed_domain_list":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM SharingAllowedDomainList property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"sharing_blocked_domain_list":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM SharingBlockedDomainList property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"sharing_capability":                                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM SharingCapability property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"sharing_domain_restriction_mode":                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM SharingDomainRestrictionMode property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"show_people_picker_suggestions_for_guest_users":     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM ShowPeoplePickerSuggestionsForGuestUsers property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"social_bar_on_site_pages_disabled":                  schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM SocialBarOnSitePagesDisabled property.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"title":                                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the CSOM Title property.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *siteResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *siteResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan siteModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := spo.SetSPOSiteParams{}
	sp.Identity = plan.Identity.ValueString()
	if !plan.AllowDownloadingNonWebViewableFiles.IsUnknown() && !plan.AllowDownloadingNonWebViewableFiles.IsNull() {
		sp.AllowDownloadingNonWebViewableFiles = plan.AllowDownloadingNonWebViewableFiles.ValueBoolPointer()
	}
	if !plan.AllowEditing.IsUnknown() && !plan.AllowEditing.IsNull() {
		sp.AllowEditing = plan.AllowEditing.ValueBoolPointer()
	}
	if !plan.AllowFileArchive.IsUnknown() && !plan.AllowFileArchive.IsNull() {
		sp.AllowFileArchive = plan.AllowFileArchive.ValueBoolPointer()
	}
	if !plan.AllowSelfServiceUpgrade.IsUnknown() && !plan.AllowSelfServiceUpgrade.IsNull() {
		sp.AllowSelfServiceUpgrade = plan.AllowSelfServiceUpgrade.ValueBoolPointer()
	}
	if !plan.AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled.IsUnknown() && !plan.AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled.IsNull() {
		sp.AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled = plan.AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled.ValueBoolPointer()
	}
	if !plan.AnonymousLinkExpirationInDays.IsUnknown() && !plan.AnonymousLinkExpirationInDays.IsNull() {
		sp.AnonymousLinkExpirationInDays = plan.AnonymousLinkExpirationInDays.ValueInt64Pointer()
	}
	if !plan.ApplyToExistingDocumentLibraries.IsUnknown() && !plan.ApplyToExistingDocumentLibraries.IsNull() {
		sp.ApplyToExistingDocumentLibraries = plan.ApplyToExistingDocumentLibraries.ValueBoolPointer()
	}
	if !plan.ApplyToNewDocumentLibraries.IsUnknown() && !plan.ApplyToNewDocumentLibraries.IsNull() {
		sp.ApplyToNewDocumentLibraries = plan.ApplyToNewDocumentLibraries.ValueBoolPointer()
	}
	if !plan.AuthenticationContextName.IsUnknown() && !plan.AuthenticationContextName.IsNull() {
		sp.AuthenticationContextName = plan.AuthenticationContextName.ValueStringPointer()
	}
	if !plan.BlockDownloadLinksFileType.IsUnknown() && !plan.BlockDownloadLinksFileType.IsNull() {
		sp.BlockDownloadLinksFileType = plan.BlockDownloadLinksFileType.ValueStringPointer()
	}
	if !plan.BlockDownloadPolicy.IsUnknown() && !plan.BlockDownloadPolicy.IsNull() {
		sp.BlockDownloadPolicy = plan.BlockDownloadPolicy.ValueBoolPointer()
	}
	if !plan.BlockGuestsAsSiteAdmin.IsUnknown() && !plan.BlockGuestsAsSiteAdmin.IsNull() {
		sp.BlockGuestsAsSiteAdmin = plan.BlockGuestsAsSiteAdmin.ValueStringPointer()
	}
	if !plan.ClearGroupId.IsUnknown() && !plan.ClearGroupId.IsNull() {
		sp.ClearGroupId = plan.ClearGroupId.ValueBoolPointer()
	}
	if !plan.ClearRestrictedAccessControl.IsUnknown() && !plan.ClearRestrictedAccessControl.IsNull() {
		sp.ClearRestrictedAccessControl = plan.ClearRestrictedAccessControl.ValueBoolPointer()
	}
	if !plan.CommentsOnSitePagesDisabled.IsUnknown() && !plan.CommentsOnSitePagesDisabled.IsNull() {
		sp.CommentsOnSitePagesDisabled = plan.CommentsOnSitePagesDisabled.ValueBoolPointer()
	}
	if !plan.ConditionalAccessPolicy.IsUnknown() && !plan.ConditionalAccessPolicy.IsNull() {
		sp.ConditionalAccessPolicy = plan.ConditionalAccessPolicy.ValueStringPointer()
	}
	if !plan.DefaultLinkPermission.IsUnknown() && !plan.DefaultLinkPermission.IsNull() {
		sp.DefaultLinkPermission = plan.DefaultLinkPermission.ValueStringPointer()
	}
	if !plan.DefaultLinkToExistingAccess.IsUnknown() && !plan.DefaultLinkToExistingAccess.IsNull() {
		sp.DefaultLinkToExistingAccess = plan.DefaultLinkToExistingAccess.ValueBoolPointer()
	}
	if !plan.DefaultLinkToExistingAccessReset.IsUnknown() && !plan.DefaultLinkToExistingAccessReset.IsNull() {
		sp.DefaultLinkToExistingAccessReset = plan.DefaultLinkToExistingAccessReset.ValueBoolPointer()
	}
	if !plan.DefaultMainLinkScope.IsUnknown() && !plan.DefaultMainLinkScope.IsNull() {
		sp.DefaultMainLinkScope = plan.DefaultMainLinkScope.ValueStringPointer()
	}
	if !plan.DefaultShareLinkRole.IsUnknown() && !plan.DefaultShareLinkRole.IsNull() {
		sp.DefaultShareLinkRole = plan.DefaultShareLinkRole.ValueStringPointer()
	}
	if !plan.DefaultShareLinkScope.IsUnknown() && !plan.DefaultShareLinkScope.IsNull() {
		sp.DefaultShareLinkScope = plan.DefaultShareLinkScope.ValueStringPointer()
	}
	if !plan.DefaultSharingLinkType.IsUnknown() && !plan.DefaultSharingLinkType.IsNull() {
		sp.DefaultSharingLinkType = plan.DefaultSharingLinkType.ValueStringPointer()
	}
	if !plan.DenyAddAndCustomizePages.IsUnknown() && !plan.DenyAddAndCustomizePages.IsNull() {
		sp.DenyAddAndCustomizePages = plan.DenyAddAndCustomizePages.ValueStringPointer()
	}
	if !plan.DisableAppViews.IsUnknown() && !plan.DisableAppViews.IsNull() {
		sp.DisableAppViews = plan.DisableAppViews.ValueStringPointer()
	}
	if !plan.DisableClassicPageBaselineSecurityMode.IsUnknown() && !plan.DisableClassicPageBaselineSecurityMode.IsNull() {
		sp.DisableClassicPageBaselineSecurityMode = plan.DisableClassicPageBaselineSecurityMode.ValueBoolPointer()
	}
	if !plan.DisableCompanyWideSharingLinks.IsUnknown() && !plan.DisableCompanyWideSharingLinks.IsNull() {
		sp.DisableCompanyWideSharingLinks = plan.DisableCompanyWideSharingLinks.ValueStringPointer()
	}
	if !plan.DisableFlows.IsUnknown() && !plan.DisableFlows.IsNull() {
		sp.DisableFlows = plan.DisableFlows.ValueStringPointer()
	}
	if !plan.DisableSiteBranding.IsUnknown() && !plan.DisableSiteBranding.IsNull() {
		sp.DisableSiteBranding = plan.DisableSiteBranding.ValueBoolPointer()
	}
	if !plan.EnableAutoExpirationVersionTrim.IsUnknown() && !plan.EnableAutoExpirationVersionTrim.IsNull() {
		sp.EnableAutoExpirationVersionTrim = plan.EnableAutoExpirationVersionTrim.ValueBoolPointer()
	}
	if !plan.ExcludeBlockDownloadPolicySiteOwners.IsUnknown() && !plan.ExcludeBlockDownloadPolicySiteOwners.IsNull() {
		sp.ExcludeBlockDownloadPolicySiteOwners = plan.ExcludeBlockDownloadPolicySiteOwners.ValueBoolPointer()
	}
	if !plan.ExcludeBlockDownloadSharePointGroups.IsUnknown() && !plan.ExcludeBlockDownloadSharePointGroups.IsNull() {
		sp.ExcludeBlockDownloadSharePointGroups = toStringSlice(ctx, plan.ExcludeBlockDownloadSharePointGroups, &resp.Diagnostics)
	}
	if !plan.ExcludedBlockDownloadGroupIds.IsUnknown() && !plan.ExcludedBlockDownloadGroupIds.IsNull() {
		sp.ExcludedBlockDownloadGroupIds = toStringSlice(ctx, plan.ExcludedBlockDownloadGroupIds, &resp.Diagnostics)
	}
	if !plan.ExpireVersionsAfterDays.IsUnknown() && !plan.ExpireVersionsAfterDays.IsNull() {
		sp.ExpireVersionsAfterDays = plan.ExpireVersionsAfterDays.ValueInt64Pointer()
	}
	if !plan.ExternalUserExpirationInDays.IsUnknown() && !plan.ExternalUserExpirationInDays.IsNull() {
		sp.ExternalUserExpirationInDays = plan.ExternalUserExpirationInDays.ValueInt64Pointer()
	}
	if !plan.FileTypesForVersionExpiration.IsUnknown() && !plan.FileTypesForVersionExpiration.IsNull() {
		sp.FileTypesForVersionExpiration = toStringSlice(ctx, plan.FileTypesForVersionExpiration, &resp.Diagnostics)
	}
	if !plan.HidePeoplePreviewingFiles.IsUnknown() && !plan.HidePeoplePreviewingFiles.IsNull() {
		sp.HidePeoplePreviewingFiles = plan.HidePeoplePreviewingFiles.ValueBoolPointer()
	}
	if !plan.HidePeopleWhoHaveListsOpen.IsUnknown() && !plan.HidePeopleWhoHaveListsOpen.IsNull() {
		sp.HidePeopleWhoHaveListsOpen = plan.HidePeopleWhoHaveListsOpen.ValueBoolPointer()
	}
	if !plan.InheritVersionPolicyFromTenant.IsUnknown() && !plan.InheritVersionPolicyFromTenant.IsNull() {
		sp.InheritVersionPolicyFromTenant = plan.InheritVersionPolicyFromTenant.ValueBoolPointer()
	}
	if !plan.IsAuthoritative.IsUnknown() && !plan.IsAuthoritative.IsNull() {
		sp.IsAuthoritative = plan.IsAuthoritative.ValueBoolPointer()
	}
	if !plan.LimitedAccessFileType.IsUnknown() && !plan.LimitedAccessFileType.IsNull() {
		sp.LimitedAccessFileType = plan.LimitedAccessFileType.ValueStringPointer()
	}
	if !plan.ListsShowHeaderAndNavigation.IsUnknown() && !plan.ListsShowHeaderAndNavigation.IsNull() {
		sp.ListsShowHeaderAndNavigation = plan.ListsShowHeaderAndNavigation.ValueBoolPointer()
	}
	if !plan.LockState.IsUnknown() && !plan.LockState.IsNull() {
		sp.LockState = plan.LockState.ValueStringPointer()
	}
	if !plan.LoopDefaultSharingLinkRole.IsUnknown() && !plan.LoopDefaultSharingLinkRole.IsNull() {
		sp.LoopDefaultSharingLinkRole = plan.LoopDefaultSharingLinkRole.ValueStringPointer()
	}
	if !plan.LoopDefaultSharingLinkScope.IsUnknown() && !plan.LoopDefaultSharingLinkScope.IsNull() {
		sp.LoopDefaultSharingLinkScope = plan.LoopDefaultSharingLinkScope.ValueStringPointer()
	}
	if !plan.MajorVersionLimit.IsUnknown() && !plan.MajorVersionLimit.IsNull() {
		sp.MajorVersionLimit = plan.MajorVersionLimit.ValueInt64Pointer()
	}
	if !plan.MajorWithMinorVersionsLimit.IsUnknown() && !plan.MajorWithMinorVersionsLimit.IsNull() {
		sp.MajorWithMinorVersionsLimit = plan.MajorWithMinorVersionsLimit.ValueInt64Pointer()
	}
	if !plan.MediaTranscription.IsUnknown() && !plan.MediaTranscription.IsNull() {
		sp.MediaTranscription = plan.MediaTranscription.ValueStringPointer()
	}
	if !plan.OverrideBlockUserInfoVisibility.IsUnknown() && !plan.OverrideBlockUserInfoVisibility.IsNull() {
		sp.OverrideBlockUserInfoVisibility = plan.OverrideBlockUserInfoVisibility.ValueStringPointer()
	}
	if !plan.OverrideSharingCapability.IsUnknown() && !plan.OverrideSharingCapability.IsNull() {
		sp.OverrideSharingCapability = plan.OverrideSharingCapability.ValueBoolPointer()
	}
	if !plan.OverrideTenantAnonymousLinkExpirationPolicy.IsUnknown() && !plan.OverrideTenantAnonymousLinkExpirationPolicy.IsNull() {
		sp.OverrideTenantAnonymousLinkExpirationPolicy = plan.OverrideTenantAnonymousLinkExpirationPolicy.ValueBoolPointer()
	}
	if !plan.OverrideTenantExternalUserExpirationPolicy.IsUnknown() && !plan.OverrideTenantExternalUserExpirationPolicy.IsNull() {
		sp.OverrideTenantExternalUserExpirationPolicy = plan.OverrideTenantExternalUserExpirationPolicy.ValueBoolPointer()
	}
	if !plan.Owner.IsUnknown() && !plan.Owner.IsNull() {
		sp.Owner = plan.Owner.ValueStringPointer()
	}
	if !plan.ReadOnlyForBlockDownloadPolicy.IsUnknown() && !plan.ReadOnlyForBlockDownloadPolicy.IsNull() {
		sp.ReadOnlyForBlockDownloadPolicy = plan.ReadOnlyForBlockDownloadPolicy.ValueBoolPointer()
	}
	if !plan.ReadOnlyForUnmanagedDevices.IsUnknown() && !plan.ReadOnlyForUnmanagedDevices.IsNull() {
		sp.ReadOnlyForUnmanagedDevices = plan.ReadOnlyForUnmanagedDevices.ValueBoolPointer()
	}
	if !plan.RemoveVersionExpirationFileTypeOverride.IsUnknown() && !plan.RemoveVersionExpirationFileTypeOverride.IsNull() {
		sp.RemoveVersionExpirationFileTypeOverride = toStringSlice(ctx, plan.RemoveVersionExpirationFileTypeOverride, &resp.Diagnostics)
	}
	if !plan.RequestFilesLinkEnabled.IsUnknown() && !plan.RequestFilesLinkEnabled.IsNull() {
		sp.RequestFilesLinkEnabled = plan.RequestFilesLinkEnabled.ValueBoolPointer()
	}
	if !plan.RequestFilesLinkExpirationInDays.IsUnknown() && !plan.RequestFilesLinkExpirationInDays.IsNull() {
		sp.RequestFilesLinkExpirationInDays = plan.RequestFilesLinkExpirationInDays.ValueInt64Pointer()
	}
	if !plan.RestrictContentOrgWideSearch.IsUnknown() && !plan.RestrictContentOrgWideSearch.IsNull() {
		sp.RestrictContentOrgWideSearch = plan.RestrictContentOrgWideSearch.ValueBoolPointer()
	}
	if !plan.RestrictedAccessControl.IsUnknown() && !plan.RestrictedAccessControl.IsNull() {
		sp.RestrictedAccessControl = plan.RestrictedAccessControl.ValueBoolPointer()
	}
	if !plan.RestrictedAccessControlGroups.IsUnknown() && !plan.RestrictedAccessControlGroups.IsNull() {
		sp.RestrictedAccessControlGroups = toStringSlice(ctx, plan.RestrictedAccessControlGroups, &resp.Diagnostics)
	}
	if !plan.RestrictedContentDiscoveryforCopilotAndAgents.IsUnknown() && !plan.RestrictedContentDiscoveryforCopilotAndAgents.IsNull() {
		sp.RestrictedContentDiscoveryforCopilotAndAgents = plan.RestrictedContentDiscoveryforCopilotAndAgents.ValueBoolPointer()
	}
	if !plan.SandboxedCodeActivationCapability.IsUnknown() && !plan.SandboxedCodeActivationCapability.IsNull() {
		sp.SandboxedCodeActivationCapability = plan.SandboxedCodeActivationCapability.ValueStringPointer()
	}
	if !plan.SensitivityLabel.IsUnknown() && !plan.SensitivityLabel.IsNull() {
		sp.SensitivityLabel = plan.SensitivityLabel.ValueStringPointer()
	}
	if !plan.SharingAllowedDomainList.IsUnknown() && !plan.SharingAllowedDomainList.IsNull() {
		sp.SharingAllowedDomainList = plan.SharingAllowedDomainList.ValueStringPointer()
	}
	if !plan.SharingBlockedDomainList.IsUnknown() && !plan.SharingBlockedDomainList.IsNull() {
		sp.SharingBlockedDomainList = plan.SharingBlockedDomainList.ValueStringPointer()
	}
	if !plan.SharingCapability.IsUnknown() && !plan.SharingCapability.IsNull() {
		sp.SharingCapability = plan.SharingCapability.ValueStringPointer()
	}
	if !plan.SharingDomainRestrictionMode.IsUnknown() && !plan.SharingDomainRestrictionMode.IsNull() {
		sp.SharingDomainRestrictionMode = plan.SharingDomainRestrictionMode.ValueStringPointer()
	}
	if !plan.ShowPeoplePickerSuggestionsForGuestUsers.IsUnknown() && !plan.ShowPeoplePickerSuggestionsForGuestUsers.IsNull() {
		sp.ShowPeoplePickerSuggestionsForGuestUsers = plan.ShowPeoplePickerSuggestionsForGuestUsers.ValueBoolPointer()
	}
	if !plan.SocialBarOnSitePagesDisabled.IsUnknown() && !plan.SocialBarOnSitePagesDisabled.IsNull() {
		sp.SocialBarOnSitePagesDisabled = plan.SocialBarOnSitePagesDisabled.ValueBoolPointer()
	}
	if !plan.Title.IsUnknown() && !plan.Title.IsNull() {
		sp.Title = plan.Title.ValueStringPointer()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPOSite(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-Site failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *siteResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state siteModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *siteResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state siteModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := spo.SetSPOSiteParams{}
	sp.Identity = id
	if !plan.AllowDownloadingNonWebViewableFiles.Equal(state.AllowDownloadingNonWebViewableFiles) {
		sp.AllowDownloadingNonWebViewableFiles = plan.AllowDownloadingNonWebViewableFiles.ValueBoolPointer()
	}
	if !plan.AllowEditing.Equal(state.AllowEditing) {
		sp.AllowEditing = plan.AllowEditing.ValueBoolPointer()
	}
	if !plan.AllowFileArchive.Equal(state.AllowFileArchive) {
		sp.AllowFileArchive = plan.AllowFileArchive.ValueBoolPointer()
	}
	if !plan.AllowSelfServiceUpgrade.Equal(state.AllowSelfServiceUpgrade) {
		sp.AllowSelfServiceUpgrade = plan.AllowSelfServiceUpgrade.ValueBoolPointer()
	}
	if !plan.AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled.Equal(state.AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled) {
		sp.AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled = plan.AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled.ValueBoolPointer()
	}
	if !plan.AnonymousLinkExpirationInDays.Equal(state.AnonymousLinkExpirationInDays) {
		sp.AnonymousLinkExpirationInDays = plan.AnonymousLinkExpirationInDays.ValueInt64Pointer()
	}
	if !plan.ApplyToExistingDocumentLibraries.Equal(state.ApplyToExistingDocumentLibraries) {
		sp.ApplyToExistingDocumentLibraries = plan.ApplyToExistingDocumentLibraries.ValueBoolPointer()
	}
	if !plan.ApplyToNewDocumentLibraries.Equal(state.ApplyToNewDocumentLibraries) {
		sp.ApplyToNewDocumentLibraries = plan.ApplyToNewDocumentLibraries.ValueBoolPointer()
	}
	if !plan.AuthenticationContextName.Equal(state.AuthenticationContextName) {
		sp.AuthenticationContextName = plan.AuthenticationContextName.ValueStringPointer()
	}
	if !plan.BlockDownloadLinksFileType.Equal(state.BlockDownloadLinksFileType) {
		sp.BlockDownloadLinksFileType = plan.BlockDownloadLinksFileType.ValueStringPointer()
	}
	if !plan.BlockDownloadPolicy.Equal(state.BlockDownloadPolicy) {
		sp.BlockDownloadPolicy = plan.BlockDownloadPolicy.ValueBoolPointer()
	}
	if !plan.BlockGuestsAsSiteAdmin.Equal(state.BlockGuestsAsSiteAdmin) {
		sp.BlockGuestsAsSiteAdmin = plan.BlockGuestsAsSiteAdmin.ValueStringPointer()
	}
	if !plan.ClearGroupId.Equal(state.ClearGroupId) {
		sp.ClearGroupId = plan.ClearGroupId.ValueBoolPointer()
	}
	if !plan.ClearRestrictedAccessControl.Equal(state.ClearRestrictedAccessControl) {
		sp.ClearRestrictedAccessControl = plan.ClearRestrictedAccessControl.ValueBoolPointer()
	}
	if !plan.CommentsOnSitePagesDisabled.Equal(state.CommentsOnSitePagesDisabled) {
		sp.CommentsOnSitePagesDisabled = plan.CommentsOnSitePagesDisabled.ValueBoolPointer()
	}
	if !plan.ConditionalAccessPolicy.Equal(state.ConditionalAccessPolicy) {
		sp.ConditionalAccessPolicy = plan.ConditionalAccessPolicy.ValueStringPointer()
	}
	if !plan.DefaultLinkPermission.Equal(state.DefaultLinkPermission) {
		sp.DefaultLinkPermission = plan.DefaultLinkPermission.ValueStringPointer()
	}
	if !plan.DefaultLinkToExistingAccess.Equal(state.DefaultLinkToExistingAccess) {
		sp.DefaultLinkToExistingAccess = plan.DefaultLinkToExistingAccess.ValueBoolPointer()
	}
	if !plan.DefaultLinkToExistingAccessReset.Equal(state.DefaultLinkToExistingAccessReset) {
		sp.DefaultLinkToExistingAccessReset = plan.DefaultLinkToExistingAccessReset.ValueBoolPointer()
	}
	if !plan.DefaultMainLinkScope.Equal(state.DefaultMainLinkScope) {
		sp.DefaultMainLinkScope = plan.DefaultMainLinkScope.ValueStringPointer()
	}
	if !plan.DefaultShareLinkRole.Equal(state.DefaultShareLinkRole) {
		sp.DefaultShareLinkRole = plan.DefaultShareLinkRole.ValueStringPointer()
	}
	if !plan.DefaultShareLinkScope.Equal(state.DefaultShareLinkScope) {
		sp.DefaultShareLinkScope = plan.DefaultShareLinkScope.ValueStringPointer()
	}
	if !plan.DefaultSharingLinkType.Equal(state.DefaultSharingLinkType) {
		sp.DefaultSharingLinkType = plan.DefaultSharingLinkType.ValueStringPointer()
	}
	if !plan.DenyAddAndCustomizePages.Equal(state.DenyAddAndCustomizePages) {
		sp.DenyAddAndCustomizePages = plan.DenyAddAndCustomizePages.ValueStringPointer()
	}
	if !plan.DisableAppViews.Equal(state.DisableAppViews) {
		sp.DisableAppViews = plan.DisableAppViews.ValueStringPointer()
	}
	if !plan.DisableClassicPageBaselineSecurityMode.Equal(state.DisableClassicPageBaselineSecurityMode) {
		sp.DisableClassicPageBaselineSecurityMode = plan.DisableClassicPageBaselineSecurityMode.ValueBoolPointer()
	}
	if !plan.DisableCompanyWideSharingLinks.Equal(state.DisableCompanyWideSharingLinks) {
		sp.DisableCompanyWideSharingLinks = plan.DisableCompanyWideSharingLinks.ValueStringPointer()
	}
	if !plan.DisableFlows.Equal(state.DisableFlows) {
		sp.DisableFlows = plan.DisableFlows.ValueStringPointer()
	}
	if !plan.DisableSiteBranding.Equal(state.DisableSiteBranding) {
		sp.DisableSiteBranding = plan.DisableSiteBranding.ValueBoolPointer()
	}
	if !plan.EnableAutoExpirationVersionTrim.Equal(state.EnableAutoExpirationVersionTrim) {
		sp.EnableAutoExpirationVersionTrim = plan.EnableAutoExpirationVersionTrim.ValueBoolPointer()
	}
	if !plan.ExcludeBlockDownloadPolicySiteOwners.Equal(state.ExcludeBlockDownloadPolicySiteOwners) {
		sp.ExcludeBlockDownloadPolicySiteOwners = plan.ExcludeBlockDownloadPolicySiteOwners.ValueBoolPointer()
	}
	if !plan.ExcludeBlockDownloadSharePointGroups.Equal(state.ExcludeBlockDownloadSharePointGroups) {
		sp.ExcludeBlockDownloadSharePointGroups = toStringSlice(ctx, plan.ExcludeBlockDownloadSharePointGroups, &resp.Diagnostics)
	}
	if !plan.ExcludedBlockDownloadGroupIds.Equal(state.ExcludedBlockDownloadGroupIds) {
		sp.ExcludedBlockDownloadGroupIds = toStringSlice(ctx, plan.ExcludedBlockDownloadGroupIds, &resp.Diagnostics)
	}
	if !plan.ExpireVersionsAfterDays.Equal(state.ExpireVersionsAfterDays) {
		sp.ExpireVersionsAfterDays = plan.ExpireVersionsAfterDays.ValueInt64Pointer()
	}
	if !plan.ExternalUserExpirationInDays.Equal(state.ExternalUserExpirationInDays) {
		sp.ExternalUserExpirationInDays = plan.ExternalUserExpirationInDays.ValueInt64Pointer()
	}
	if !plan.FileTypesForVersionExpiration.Equal(state.FileTypesForVersionExpiration) {
		sp.FileTypesForVersionExpiration = toStringSlice(ctx, plan.FileTypesForVersionExpiration, &resp.Diagnostics)
	}
	if !plan.HidePeoplePreviewingFiles.Equal(state.HidePeoplePreviewingFiles) {
		sp.HidePeoplePreviewingFiles = plan.HidePeoplePreviewingFiles.ValueBoolPointer()
	}
	if !plan.HidePeopleWhoHaveListsOpen.Equal(state.HidePeopleWhoHaveListsOpen) {
		sp.HidePeopleWhoHaveListsOpen = plan.HidePeopleWhoHaveListsOpen.ValueBoolPointer()
	}
	if !plan.InheritVersionPolicyFromTenant.Equal(state.InheritVersionPolicyFromTenant) {
		sp.InheritVersionPolicyFromTenant = plan.InheritVersionPolicyFromTenant.ValueBoolPointer()
	}
	if !plan.IsAuthoritative.Equal(state.IsAuthoritative) {
		sp.IsAuthoritative = plan.IsAuthoritative.ValueBoolPointer()
	}
	if !plan.LimitedAccessFileType.Equal(state.LimitedAccessFileType) {
		sp.LimitedAccessFileType = plan.LimitedAccessFileType.ValueStringPointer()
	}
	if !plan.ListsShowHeaderAndNavigation.Equal(state.ListsShowHeaderAndNavigation) {
		sp.ListsShowHeaderAndNavigation = plan.ListsShowHeaderAndNavigation.ValueBoolPointer()
	}
	if !plan.LockState.Equal(state.LockState) {
		sp.LockState = plan.LockState.ValueStringPointer()
	}
	if !plan.LoopDefaultSharingLinkRole.Equal(state.LoopDefaultSharingLinkRole) {
		sp.LoopDefaultSharingLinkRole = plan.LoopDefaultSharingLinkRole.ValueStringPointer()
	}
	if !plan.LoopDefaultSharingLinkScope.Equal(state.LoopDefaultSharingLinkScope) {
		sp.LoopDefaultSharingLinkScope = plan.LoopDefaultSharingLinkScope.ValueStringPointer()
	}
	if !plan.MajorVersionLimit.Equal(state.MajorVersionLimit) {
		sp.MajorVersionLimit = plan.MajorVersionLimit.ValueInt64Pointer()
	}
	if !plan.MajorWithMinorVersionsLimit.Equal(state.MajorWithMinorVersionsLimit) {
		sp.MajorWithMinorVersionsLimit = plan.MajorWithMinorVersionsLimit.ValueInt64Pointer()
	}
	if !plan.MediaTranscription.Equal(state.MediaTranscription) {
		sp.MediaTranscription = plan.MediaTranscription.ValueStringPointer()
	}
	if !plan.OverrideBlockUserInfoVisibility.Equal(state.OverrideBlockUserInfoVisibility) {
		sp.OverrideBlockUserInfoVisibility = plan.OverrideBlockUserInfoVisibility.ValueStringPointer()
	}
	if !plan.OverrideSharingCapability.Equal(state.OverrideSharingCapability) {
		sp.OverrideSharingCapability = plan.OverrideSharingCapability.ValueBoolPointer()
	}
	if !plan.OverrideTenantAnonymousLinkExpirationPolicy.Equal(state.OverrideTenantAnonymousLinkExpirationPolicy) {
		sp.OverrideTenantAnonymousLinkExpirationPolicy = plan.OverrideTenantAnonymousLinkExpirationPolicy.ValueBoolPointer()
	}
	if !plan.OverrideTenantExternalUserExpirationPolicy.Equal(state.OverrideTenantExternalUserExpirationPolicy) {
		sp.OverrideTenantExternalUserExpirationPolicy = plan.OverrideTenantExternalUserExpirationPolicy.ValueBoolPointer()
	}
	if !plan.Owner.Equal(state.Owner) {
		sp.Owner = plan.Owner.ValueStringPointer()
	}
	if !plan.ReadOnlyForBlockDownloadPolicy.Equal(state.ReadOnlyForBlockDownloadPolicy) {
		sp.ReadOnlyForBlockDownloadPolicy = plan.ReadOnlyForBlockDownloadPolicy.ValueBoolPointer()
	}
	if !plan.ReadOnlyForUnmanagedDevices.Equal(state.ReadOnlyForUnmanagedDevices) {
		sp.ReadOnlyForUnmanagedDevices = plan.ReadOnlyForUnmanagedDevices.ValueBoolPointer()
	}
	if !plan.RemoveVersionExpirationFileTypeOverride.Equal(state.RemoveVersionExpirationFileTypeOverride) {
		sp.RemoveVersionExpirationFileTypeOverride = toStringSlice(ctx, plan.RemoveVersionExpirationFileTypeOverride, &resp.Diagnostics)
	}
	if !plan.RequestFilesLinkEnabled.Equal(state.RequestFilesLinkEnabled) {
		sp.RequestFilesLinkEnabled = plan.RequestFilesLinkEnabled.ValueBoolPointer()
	}
	if !plan.RequestFilesLinkExpirationInDays.Equal(state.RequestFilesLinkExpirationInDays) {
		sp.RequestFilesLinkExpirationInDays = plan.RequestFilesLinkExpirationInDays.ValueInt64Pointer()
	}
	if !plan.RestrictContentOrgWideSearch.Equal(state.RestrictContentOrgWideSearch) {
		sp.RestrictContentOrgWideSearch = plan.RestrictContentOrgWideSearch.ValueBoolPointer()
	}
	if !plan.RestrictedAccessControl.Equal(state.RestrictedAccessControl) {
		sp.RestrictedAccessControl = plan.RestrictedAccessControl.ValueBoolPointer()
	}
	if !plan.RestrictedAccessControlGroups.Equal(state.RestrictedAccessControlGroups) {
		sp.RestrictedAccessControlGroups = toStringSlice(ctx, plan.RestrictedAccessControlGroups, &resp.Diagnostics)
	}
	if !plan.RestrictedContentDiscoveryforCopilotAndAgents.Equal(state.RestrictedContentDiscoveryforCopilotAndAgents) {
		sp.RestrictedContentDiscoveryforCopilotAndAgents = plan.RestrictedContentDiscoveryforCopilotAndAgents.ValueBoolPointer()
	}
	if !plan.SandboxedCodeActivationCapability.Equal(state.SandboxedCodeActivationCapability) {
		sp.SandboxedCodeActivationCapability = plan.SandboxedCodeActivationCapability.ValueStringPointer()
	}
	if !plan.SensitivityLabel.Equal(state.SensitivityLabel) {
		sp.SensitivityLabel = plan.SensitivityLabel.ValueStringPointer()
	}
	if !plan.SharingAllowedDomainList.Equal(state.SharingAllowedDomainList) {
		sp.SharingAllowedDomainList = plan.SharingAllowedDomainList.ValueStringPointer()
	}
	if !plan.SharingBlockedDomainList.Equal(state.SharingBlockedDomainList) {
		sp.SharingBlockedDomainList = plan.SharingBlockedDomainList.ValueStringPointer()
	}
	if !plan.SharingCapability.Equal(state.SharingCapability) {
		sp.SharingCapability = plan.SharingCapability.ValueStringPointer()
	}
	if !plan.SharingDomainRestrictionMode.Equal(state.SharingDomainRestrictionMode) {
		sp.SharingDomainRestrictionMode = plan.SharingDomainRestrictionMode.ValueStringPointer()
	}
	if !plan.ShowPeoplePickerSuggestionsForGuestUsers.Equal(state.ShowPeoplePickerSuggestionsForGuestUsers) {
		sp.ShowPeoplePickerSuggestionsForGuestUsers = plan.ShowPeoplePickerSuggestionsForGuestUsers.ValueBoolPointer()
	}
	if !plan.SocialBarOnSitePagesDisabled.Equal(state.SocialBarOnSitePagesDisabled) {
		sp.SocialBarOnSitePagesDisabled = plan.SocialBarOnSitePagesDisabled.ValueBoolPointer()
	}
	if !plan.Title.Equal(state.Title) {
		sp.Title = plan.Title.ValueStringPointer()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPOSite(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-Site failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"AuthenticationContextName":         cfg.AuthenticationContextName,
		"BlockDownloadLinksFileType":        cfg.BlockDownloadLinksFileType,
		"BlockGuestsAsSiteAdmin":            cfg.BlockGuestsAsSiteAdmin,
		"ConditionalAccessPolicy":           cfg.ConditionalAccessPolicy,
		"DefaultLinkPermission":             cfg.DefaultLinkPermission,
		"DefaultMainLinkScope":              cfg.DefaultMainLinkScope,
		"DefaultShareLinkRole":              cfg.DefaultShareLinkRole,
		"DefaultShareLinkScope":             cfg.DefaultShareLinkScope,
		"DefaultSharingLinkType":            cfg.DefaultSharingLinkType,
		"DenyAddAndCustomizePages":          cfg.DenyAddAndCustomizePages,
		"DisableAppViews":                   cfg.DisableAppViews,
		"DisableCompanyWideSharingLinks":    cfg.DisableCompanyWideSharingLinks,
		"DisableFlows":                      cfg.DisableFlows,
		"LimitedAccessFileType":             cfg.LimitedAccessFileType,
		"LockState":                         cfg.LockState,
		"LoopDefaultSharingLinkRole":        cfg.LoopDefaultSharingLinkRole,
		"LoopDefaultSharingLinkScope":       cfg.LoopDefaultSharingLinkScope,
		"MediaTranscription":                cfg.MediaTranscription,
		"OverrideBlockUserInfoVisibility":   cfg.OverrideBlockUserInfoVisibility,
		"Owner":                             cfg.Owner,
		"SandboxedCodeActivationCapability": cfg.SandboxedCodeActivationCapability,
		"SensitivityLabel":                  cfg.SensitivityLabel,
		"SharingAllowedDomainList":          cfg.SharingAllowedDomainList,
		"SharingBlockedDomainList":          cfg.SharingBlockedDomainList,
		"SharingCapability":                 cfg.SharingCapability,
		"SharingDomainRestrictionMode":      cfg.SharingDomainRestrictionMode,
		"Title":                             cfg.Title,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *siteResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("Site configuration not deleted", "This resource manages an existing Site configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *siteResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *siteResource) identityOf(m siteModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *siteResource) refresh(ctx context.Context, identity string, m *siteModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SPO.GetSPOSite(ctx, spo.GetSPOSiteParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-Site failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readSite(ctx, obj, m)
	return true
}

func readSite(ctx context.Context, obj map[string]any, m *siteModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.AllowDownloadingNonWebViewableFiles = types.BoolValue(getBool(obj, "AllowDownloadingNonWebViewableFiles"))
	m.AllowEditing = types.BoolValue(getBool(obj, "AllowEditing"))
	m.AllowFileArchive = types.BoolValue(getBool(obj, "AllowFileArchive"))
	m.AllowSelfServiceUpgrade = types.BoolValue(getBool(obj, "AllowSelfServiceUpgrade"))
	m.AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled = types.BoolValue(getBool(obj, "AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled"))
	m.AnonymousLinkExpirationInDays = types.Int64Value(getInt(obj, "AnonymousLinkExpirationInDays"))
	m.ApplyToExistingDocumentLibraries = types.BoolValue(getBool(obj, "ApplyToExistingDocumentLibraries"))
	m.ApplyToNewDocumentLibraries = types.BoolValue(getBool(obj, "ApplyToNewDocumentLibraries"))
	m.AuthenticationContextName = types.StringValue(getString(obj, "AuthenticationContextName"))
	m.BlockDownloadLinksFileType = types.StringValue(getString(obj, "BlockDownloadLinksFileType"))
	m.BlockDownloadPolicy = types.BoolValue(getBool(obj, "BlockDownloadPolicy"))
	m.BlockGuestsAsSiteAdmin = types.StringValue(getString(obj, "BlockGuestsAsSiteAdmin"))
	m.ClearGroupId = types.BoolValue(getBool(obj, "ClearGroupId"))
	m.ClearRestrictedAccessControl = types.BoolValue(getBool(obj, "ClearRestrictedAccessControl"))
	m.CommentsOnSitePagesDisabled = types.BoolValue(getBool(obj, "CommentsOnSitePagesDisabled"))
	m.ConditionalAccessPolicy = types.StringValue(getString(obj, "ConditionalAccessPolicy"))
	m.DefaultLinkPermission = types.StringValue(getString(obj, "DefaultLinkPermission"))
	m.DefaultLinkToExistingAccess = types.BoolValue(getBool(obj, "DefaultLinkToExistingAccess"))
	m.DefaultLinkToExistingAccessReset = types.BoolValue(getBool(obj, "DefaultLinkToExistingAccessReset"))
	m.DefaultMainLinkScope = types.StringValue(getString(obj, "DefaultMainLinkScope"))
	m.DefaultShareLinkRole = types.StringValue(getString(obj, "DefaultShareLinkRole"))
	m.DefaultShareLinkScope = types.StringValue(getString(obj, "DefaultShareLinkScope"))
	m.DefaultSharingLinkType = types.StringValue(getString(obj, "DefaultSharingLinkType"))
	m.DenyAddAndCustomizePages = types.StringValue(getString(obj, "DenyAddAndCustomizePages"))
	m.DisableAppViews = types.StringValue(getString(obj, "DisableAppViews"))
	m.DisableClassicPageBaselineSecurityMode = types.BoolValue(getBool(obj, "DisableClassicPageBaselineSecurityMode"))
	m.DisableCompanyWideSharingLinks = types.StringValue(getString(obj, "DisableCompanyWideSharingLinks"))
	m.DisableFlows = types.StringValue(getString(obj, "DisableFlows"))
	m.DisableSiteBranding = types.BoolValue(getBool(obj, "DisableSiteBranding"))
	m.EnableAutoExpirationVersionTrim = types.BoolValue(getBool(obj, "EnableAutoExpirationVersionTrim"))
	m.ExcludeBlockDownloadPolicySiteOwners = types.BoolValue(getBool(obj, "ExcludeBlockDownloadPolicySiteOwners"))
	m.ExcludeBlockDownloadSharePointGroups = stringSetValue(ctx, getStringSlice(obj, "ExcludeBlockDownloadSharePointGroups"))
	m.ExcludedBlockDownloadGroupIds = stringSetValue(ctx, getStringSlice(obj, "ExcludedBlockDownloadGroupIds"))
	m.ExpireVersionsAfterDays = types.Int64Value(getInt(obj, "ExpireVersionsAfterDays"))
	m.ExternalUserExpirationInDays = types.Int64Value(getInt(obj, "ExternalUserExpirationInDays"))
	m.FileTypesForVersionExpiration = stringSetValue(ctx, getStringSlice(obj, "FileTypesForVersionExpiration"))
	m.HidePeoplePreviewingFiles = types.BoolValue(getBool(obj, "HidePeoplePreviewingFiles"))
	m.HidePeopleWhoHaveListsOpen = types.BoolValue(getBool(obj, "HidePeopleWhoHaveListsOpen"))
	m.InheritVersionPolicyFromTenant = types.BoolValue(getBool(obj, "InheritVersionPolicyFromTenant"))
	m.IsAuthoritative = types.BoolValue(getBool(obj, "IsAuthoritative"))
	m.LimitedAccessFileType = types.StringValue(getString(obj, "LimitedAccessFileType"))
	m.ListsShowHeaderAndNavigation = types.BoolValue(getBool(obj, "ListsShowHeaderAndNavigation"))
	m.LockState = types.StringValue(getString(obj, "LockState"))
	m.LoopDefaultSharingLinkRole = types.StringValue(getString(obj, "LoopDefaultSharingLinkRole"))
	m.LoopDefaultSharingLinkScope = types.StringValue(getString(obj, "LoopDefaultSharingLinkScope"))
	m.MajorVersionLimit = types.Int64Value(getInt(obj, "MajorVersionLimit"))
	m.MajorWithMinorVersionsLimit = types.Int64Value(getInt(obj, "MajorWithMinorVersionsLimit"))
	m.MediaTranscription = types.StringValue(getString(obj, "MediaTranscription"))
	m.OverrideBlockUserInfoVisibility = types.StringValue(getString(obj, "OverrideBlockUserInfoVisibility"))
	m.OverrideSharingCapability = types.BoolValue(getBool(obj, "OverrideSharingCapability"))
	m.OverrideTenantAnonymousLinkExpirationPolicy = types.BoolValue(getBool(obj, "OverrideTenantAnonymousLinkExpirationPolicy"))
	m.OverrideTenantExternalUserExpirationPolicy = types.BoolValue(getBool(obj, "OverrideTenantExternalUserExpirationPolicy"))
	m.Owner = types.StringValue(getString(obj, "Owner"))
	m.ReadOnlyForBlockDownloadPolicy = types.BoolValue(getBool(obj, "ReadOnlyForBlockDownloadPolicy"))
	m.ReadOnlyForUnmanagedDevices = types.BoolValue(getBool(obj, "ReadOnlyForUnmanagedDevices"))
	m.RemoveVersionExpirationFileTypeOverride = stringSetValue(ctx, getStringSlice(obj, "RemoveVersionExpirationFileTypeOverride"))
	m.RequestFilesLinkEnabled = types.BoolValue(getBool(obj, "RequestFilesLinkEnabled"))
	m.RequestFilesLinkExpirationInDays = types.Int64Value(getInt(obj, "RequestFilesLinkExpirationInDays"))
	m.RestrictContentOrgWideSearch = types.BoolValue(getBool(obj, "RestrictContentOrgWideSearch"))
	m.RestrictedAccessControl = types.BoolValue(getBool(obj, "RestrictedAccessControl"))
	m.RestrictedAccessControlGroups = stringSetValue(ctx, getStringSlice(obj, "RestrictedAccessControlGroups"))
	m.RestrictedContentDiscoveryforCopilotAndAgents = types.BoolValue(getBool(obj, "RestrictedContentDiscoveryforCopilotAndAgents"))
	m.SandboxedCodeActivationCapability = types.StringValue(getString(obj, "SandboxedCodeActivationCapability"))
	m.SensitivityLabel = types.StringValue(getString(obj, "SensitivityLabel"))
	m.SharingAllowedDomainList = types.StringValue(getString(obj, "SharingAllowedDomainList"))
	m.SharingBlockedDomainList = types.StringValue(getString(obj, "SharingBlockedDomainList"))
	m.SharingCapability = types.StringValue(getString(obj, "SharingCapability"))
	m.SharingDomainRestrictionMode = types.StringValue(getString(obj, "SharingDomainRestrictionMode"))
	m.ShowPeoplePickerSuggestionsForGuestUsers = types.BoolValue(getBool(obj, "ShowPeoplePickerSuggestionsForGuestUsers"))
	m.SocialBarOnSitePagesDisabled = types.BoolValue(getBool(obj, "SocialBarOnSitePagesDisabled"))
	m.Title = types.StringValue(getString(obj, "Title"))
	_ = ctx
}

func (r *siteResource) reconcileState(cfg, read *siteModel) {
	read.AllowDownloadingNonWebViewableFiles = reconcile.KeepBool(cfg.AllowDownloadingNonWebViewableFiles, read.AllowDownloadingNonWebViewableFiles)
	read.AllowEditing = reconcile.KeepBool(cfg.AllowEditing, read.AllowEditing)
	read.AllowFileArchive = reconcile.KeepBool(cfg.AllowFileArchive, read.AllowFileArchive)
	read.AllowSelfServiceUpgrade = reconcile.KeepBool(cfg.AllowSelfServiceUpgrade, read.AllowSelfServiceUpgrade)
	read.AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled = reconcile.KeepBool(cfg.AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled, read.AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled)
	read.AnonymousLinkExpirationInDays = reconcile.KeepInt64(cfg.AnonymousLinkExpirationInDays, read.AnonymousLinkExpirationInDays)
	read.ApplyToExistingDocumentLibraries = reconcile.KeepBool(cfg.ApplyToExistingDocumentLibraries, read.ApplyToExistingDocumentLibraries)
	read.ApplyToNewDocumentLibraries = reconcile.KeepBool(cfg.ApplyToNewDocumentLibraries, read.ApplyToNewDocumentLibraries)
	read.AuthenticationContextName = reconcile.KeepStr(cfg.AuthenticationContextName, read.AuthenticationContextName)
	read.BlockDownloadLinksFileType = reconcile.KeepStr(cfg.BlockDownloadLinksFileType, read.BlockDownloadLinksFileType)
	read.BlockDownloadPolicy = reconcile.KeepBool(cfg.BlockDownloadPolicy, read.BlockDownloadPolicy)
	read.BlockGuestsAsSiteAdmin = reconcile.KeepStr(cfg.BlockGuestsAsSiteAdmin, read.BlockGuestsAsSiteAdmin)
	read.ClearGroupId = reconcile.KeepBool(cfg.ClearGroupId, read.ClearGroupId)
	read.ClearRestrictedAccessControl = reconcile.KeepBool(cfg.ClearRestrictedAccessControl, read.ClearRestrictedAccessControl)
	read.CommentsOnSitePagesDisabled = reconcile.KeepBool(cfg.CommentsOnSitePagesDisabled, read.CommentsOnSitePagesDisabled)
	read.ConditionalAccessPolicy = reconcile.KeepStr(cfg.ConditionalAccessPolicy, read.ConditionalAccessPolicy)
	read.DefaultLinkPermission = reconcile.KeepStr(cfg.DefaultLinkPermission, read.DefaultLinkPermission)
	read.DefaultLinkToExistingAccess = reconcile.KeepBool(cfg.DefaultLinkToExistingAccess, read.DefaultLinkToExistingAccess)
	read.DefaultLinkToExistingAccessReset = reconcile.KeepBool(cfg.DefaultLinkToExistingAccessReset, read.DefaultLinkToExistingAccessReset)
	read.DefaultMainLinkScope = reconcile.KeepStr(cfg.DefaultMainLinkScope, read.DefaultMainLinkScope)
	read.DefaultShareLinkRole = reconcile.KeepStr(cfg.DefaultShareLinkRole, read.DefaultShareLinkRole)
	read.DefaultShareLinkScope = reconcile.KeepStr(cfg.DefaultShareLinkScope, read.DefaultShareLinkScope)
	read.DefaultSharingLinkType = reconcile.KeepStr(cfg.DefaultSharingLinkType, read.DefaultSharingLinkType)
	read.DenyAddAndCustomizePages = reconcile.KeepStr(cfg.DenyAddAndCustomizePages, read.DenyAddAndCustomizePages)
	read.DisableAppViews = reconcile.KeepStr(cfg.DisableAppViews, read.DisableAppViews)
	read.DisableClassicPageBaselineSecurityMode = reconcile.KeepBool(cfg.DisableClassicPageBaselineSecurityMode, read.DisableClassicPageBaselineSecurityMode)
	read.DisableCompanyWideSharingLinks = reconcile.KeepStr(cfg.DisableCompanyWideSharingLinks, read.DisableCompanyWideSharingLinks)
	read.DisableFlows = reconcile.KeepStr(cfg.DisableFlows, read.DisableFlows)
	read.DisableSiteBranding = reconcile.KeepBool(cfg.DisableSiteBranding, read.DisableSiteBranding)
	read.EnableAutoExpirationVersionTrim = reconcile.KeepBool(cfg.EnableAutoExpirationVersionTrim, read.EnableAutoExpirationVersionTrim)
	read.ExcludeBlockDownloadPolicySiteOwners = reconcile.KeepBool(cfg.ExcludeBlockDownloadPolicySiteOwners, read.ExcludeBlockDownloadPolicySiteOwners)
	read.ExcludeBlockDownloadSharePointGroups = reconcile.KeepSet(cfg.ExcludeBlockDownloadSharePointGroups, read.ExcludeBlockDownloadSharePointGroups)
	read.ExcludedBlockDownloadGroupIds = reconcile.KeepSet(cfg.ExcludedBlockDownloadGroupIds, read.ExcludedBlockDownloadGroupIds)
	read.ExpireVersionsAfterDays = reconcile.KeepInt64(cfg.ExpireVersionsAfterDays, read.ExpireVersionsAfterDays)
	read.ExternalUserExpirationInDays = reconcile.KeepInt64(cfg.ExternalUserExpirationInDays, read.ExternalUserExpirationInDays)
	read.FileTypesForVersionExpiration = reconcile.KeepSet(cfg.FileTypesForVersionExpiration, read.FileTypesForVersionExpiration)
	read.HidePeoplePreviewingFiles = reconcile.KeepBool(cfg.HidePeoplePreviewingFiles, read.HidePeoplePreviewingFiles)
	read.HidePeopleWhoHaveListsOpen = reconcile.KeepBool(cfg.HidePeopleWhoHaveListsOpen, read.HidePeopleWhoHaveListsOpen)
	read.InheritVersionPolicyFromTenant = reconcile.KeepBool(cfg.InheritVersionPolicyFromTenant, read.InheritVersionPolicyFromTenant)
	read.IsAuthoritative = reconcile.KeepBool(cfg.IsAuthoritative, read.IsAuthoritative)
	read.LimitedAccessFileType = reconcile.KeepStr(cfg.LimitedAccessFileType, read.LimitedAccessFileType)
	read.ListsShowHeaderAndNavigation = reconcile.KeepBool(cfg.ListsShowHeaderAndNavigation, read.ListsShowHeaderAndNavigation)
	read.LockState = reconcile.KeepStr(cfg.LockState, read.LockState)
	read.LoopDefaultSharingLinkRole = reconcile.KeepStr(cfg.LoopDefaultSharingLinkRole, read.LoopDefaultSharingLinkRole)
	read.LoopDefaultSharingLinkScope = reconcile.KeepStr(cfg.LoopDefaultSharingLinkScope, read.LoopDefaultSharingLinkScope)
	read.MajorVersionLimit = reconcile.KeepInt64(cfg.MajorVersionLimit, read.MajorVersionLimit)
	read.MajorWithMinorVersionsLimit = reconcile.KeepInt64(cfg.MajorWithMinorVersionsLimit, read.MajorWithMinorVersionsLimit)
	read.MediaTranscription = reconcile.KeepStr(cfg.MediaTranscription, read.MediaTranscription)
	read.OverrideBlockUserInfoVisibility = reconcile.KeepStr(cfg.OverrideBlockUserInfoVisibility, read.OverrideBlockUserInfoVisibility)
	read.OverrideSharingCapability = reconcile.KeepBool(cfg.OverrideSharingCapability, read.OverrideSharingCapability)
	read.OverrideTenantAnonymousLinkExpirationPolicy = reconcile.KeepBool(cfg.OverrideTenantAnonymousLinkExpirationPolicy, read.OverrideTenantAnonymousLinkExpirationPolicy)
	read.OverrideTenantExternalUserExpirationPolicy = reconcile.KeepBool(cfg.OverrideTenantExternalUserExpirationPolicy, read.OverrideTenantExternalUserExpirationPolicy)
	read.Owner = reconcile.KeepStr(cfg.Owner, read.Owner)
	read.ReadOnlyForBlockDownloadPolicy = reconcile.KeepBool(cfg.ReadOnlyForBlockDownloadPolicy, read.ReadOnlyForBlockDownloadPolicy)
	read.ReadOnlyForUnmanagedDevices = reconcile.KeepBool(cfg.ReadOnlyForUnmanagedDevices, read.ReadOnlyForUnmanagedDevices)
	read.RemoveVersionExpirationFileTypeOverride = reconcile.KeepSet(cfg.RemoveVersionExpirationFileTypeOverride, read.RemoveVersionExpirationFileTypeOverride)
	read.RequestFilesLinkEnabled = reconcile.KeepBool(cfg.RequestFilesLinkEnabled, read.RequestFilesLinkEnabled)
	read.RequestFilesLinkExpirationInDays = reconcile.KeepInt64(cfg.RequestFilesLinkExpirationInDays, read.RequestFilesLinkExpirationInDays)
	read.RestrictContentOrgWideSearch = reconcile.KeepBool(cfg.RestrictContentOrgWideSearch, read.RestrictContentOrgWideSearch)
	read.RestrictedAccessControl = reconcile.KeepBool(cfg.RestrictedAccessControl, read.RestrictedAccessControl)
	read.RestrictedAccessControlGroups = reconcile.KeepSet(cfg.RestrictedAccessControlGroups, read.RestrictedAccessControlGroups)
	read.RestrictedContentDiscoveryforCopilotAndAgents = reconcile.KeepBool(cfg.RestrictedContentDiscoveryforCopilotAndAgents, read.RestrictedContentDiscoveryforCopilotAndAgents)
	read.SandboxedCodeActivationCapability = reconcile.KeepStr(cfg.SandboxedCodeActivationCapability, read.SandboxedCodeActivationCapability)
	read.SensitivityLabel = reconcile.KeepStr(cfg.SensitivityLabel, read.SensitivityLabel)
	read.SharingAllowedDomainList = reconcile.KeepStr(cfg.SharingAllowedDomainList, read.SharingAllowedDomainList)
	read.SharingBlockedDomainList = reconcile.KeepStr(cfg.SharingBlockedDomainList, read.SharingBlockedDomainList)
	read.SharingCapability = reconcile.KeepStr(cfg.SharingCapability, read.SharingCapability)
	read.SharingDomainRestrictionMode = reconcile.KeepStr(cfg.SharingDomainRestrictionMode, read.SharingDomainRestrictionMode)
	read.ShowPeoplePickerSuggestionsForGuestUsers = reconcile.KeepBool(cfg.ShowPeoplePickerSuggestionsForGuestUsers, read.ShowPeoplePickerSuggestionsForGuestUsers)
	read.SocialBarOnSitePagesDisabled = reconcile.KeepBool(cfg.SocialBarOnSitePagesDisabled, read.SocialBarOnSitePagesDisabled)
	read.Title = reconcile.KeepStr(cfg.Title, read.Title)
}
