// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &siteDataSource{}
	_ datasource.DataSourceWithConfigure = &siteDataSource{}
)

type siteDataSource struct{ client *clients.Client }

// NewSiteDataSource looks up a Site object (Get-Site).
func NewSiteDataSource() datasource.DataSource { return &siteDataSource{} }

func (d *siteDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_site"
}

func (d *siteDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing Site object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity": schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"allow_downloading_non_web_viewable_files": schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowDownloadingNonWebViewableFiles property."},
			"allow_editing":              schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowEditing property."},
			"allow_file_archive":         schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowFileArchive property."},
			"allow_self_service_upgrade": schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowSelfServiceUpgrade property."},
			"allow_web_property_bag_update_when_deny_add_and_customize_pages_is_enabled": schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled property."},
			"anonymous_link_expiration_in_days":                                          schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM AnonymousLinkExpirationInDays property."},
			"apply_to_existing_document_libraries":                                       schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ApplyToExistingDocumentLibraries property."},
			"apply_to_new_document_libraries":                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ApplyToNewDocumentLibraries property."},
			"authentication_context_name":                                                schema.StringAttribute{Computed: true, Description: "Maps to the CSOM AuthenticationContextName property."},
			"block_download_links_file_type":                                             schema.StringAttribute{Computed: true, Description: "Maps to the CSOM BlockDownloadLinksFileType property."},
			"block_download_policy":                                                      schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM BlockDownloadPolicy property."},
			"block_guests_as_site_admin":                                                 schema.StringAttribute{Computed: true, Description: "Maps to the CSOM BlockGuestsAsSiteAdmin property."},
			"clear_group_id":                                                             schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ClearGroupId property."},
			"clear_restricted_access_control":                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ClearRestrictedAccessControl property."},
			"comments_on_site_pages_disabled":                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM CommentsOnSitePagesDisabled property."},
			"conditional_access_policy":                                                  schema.StringAttribute{Computed: true, Description: "Maps to the CSOM ConditionalAccessPolicy property."},
			"default_link_permission":                                                    schema.StringAttribute{Computed: true, Description: "Maps to the CSOM DefaultLinkPermission property."},
			"default_link_to_existing_access":                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DefaultLinkToExistingAccess property."},
			"default_link_to_existing_access_reset":                                      schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DefaultLinkToExistingAccessReset property."},
			"default_main_link_scope":                                                    schema.StringAttribute{Computed: true, Description: "Maps to the CSOM DefaultMainLinkScope property."},
			"default_share_link_role":                                                    schema.StringAttribute{Computed: true, Description: "Maps to the CSOM DefaultShareLinkRole property."},
			"default_share_link_scope":                                                   schema.StringAttribute{Computed: true, Description: "Maps to the CSOM DefaultShareLinkScope property."},
			"default_sharing_link_type":                                                  schema.StringAttribute{Computed: true, Description: "Maps to the CSOM DefaultSharingLinkType property."},
			"deny_add_and_customize_pages":                                               schema.StringAttribute{Computed: true, Description: "Maps to the CSOM DenyAddAndCustomizePages property."},
			"disable_app_views":                                                          schema.StringAttribute{Computed: true, Description: "Maps to the CSOM DisableAppViews property."},
			"disable_classic_page_baseline_security_mode":                                schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DisableClassicPageBaselineSecurityMode property."},
			"disable_company_wide_sharing_links":                                         schema.StringAttribute{Computed: true, Description: "Maps to the CSOM DisableCompanyWideSharingLinks property."},
			"disable_flows":                                                              schema.StringAttribute{Computed: true, Description: "Maps to the CSOM DisableFlows property."},
			"disable_site_branding":                                                      schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DisableSiteBranding property."},
			"enable_auto_expiration_version_trim":                                        schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnableAutoExpirationVersionTrim property."},
			"exclude_block_download_policy_site_owners":                                  schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ExcludeBlockDownloadPolicySiteOwners property."},
			"exclude_block_download_share_point_groups":                                  schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the CSOM ExcludeBlockDownloadSharePointGroups property."},
			"excluded_block_download_group_ids":                                          schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the CSOM ExcludedBlockDownloadGroupIds property."},
			"expire_versions_after_days":                                                 schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM ExpireVersionsAfterDays property."},
			"external_user_expiration_in_days":                                           schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM ExternalUserExpirationInDays property."},
			"file_types_for_version_expiration":                                          schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the CSOM FileTypesForVersionExpiration property."},
			"hide_people_previewing_files":                                               schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM HidePeoplePreviewingFiles property."},
			"hide_people_who_have_lists_open":                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM HidePeopleWhoHaveListsOpen property."},
			"inherit_version_policy_from_tenant":                                         schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM InheritVersionPolicyFromTenant property."},
			"is_authoritative":                                                           schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM IsAuthoritative property."},
			"limited_access_file_type":                                                   schema.StringAttribute{Computed: true, Description: "Maps to the CSOM LimitedAccessFileType property."},
			"lists_show_header_and_navigation":                                           schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ListsShowHeaderAndNavigation property."},
			"lock_state":                                                                 schema.StringAttribute{Computed: true, Description: "Maps to the CSOM LockState property."},
			"loop_default_sharing_link_role":                                             schema.StringAttribute{Computed: true, Description: "Maps to the CSOM LoopDefaultSharingLinkRole property."},
			"loop_default_sharing_link_scope":                                            schema.StringAttribute{Computed: true, Description: "Maps to the CSOM LoopDefaultSharingLinkScope property."},
			"major_version_limit":                                                        schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM MajorVersionLimit property."},
			"major_with_minor_versions_limit":                                            schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM MajorWithMinorVersionsLimit property."},
			"media_transcription":                                                        schema.StringAttribute{Computed: true, Description: "Maps to the CSOM MediaTranscription property."},
			"override_block_user_info_visibility":                                        schema.StringAttribute{Computed: true, Description: "Maps to the CSOM OverrideBlockUserInfoVisibility property."},
			"override_sharing_capability":                                                schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM OverrideSharingCapability property."},
			"override_tenant_anonymous_link_expiration_policy":                           schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM OverrideTenantAnonymousLinkExpirationPolicy property."},
			"override_tenant_external_user_expiration_policy":                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM OverrideTenantExternalUserExpirationPolicy property."},
			"owner":                                              schema.StringAttribute{Computed: true, Description: "Maps to the CSOM Owner property."},
			"read_only_for_block_download_policy":                schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ReadOnlyForBlockDownloadPolicy property."},
			"read_only_for_unmanaged_devices":                    schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ReadOnlyForUnmanagedDevices property."},
			"remove_version_expiration_file_type_override":       schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the CSOM RemoveVersionExpirationFileTypeOverride property."},
			"request_files_link_enabled":                         schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM RequestFilesLinkEnabled property."},
			"request_files_link_expiration_in_days":              schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM RequestFilesLinkExpirationInDays property."},
			"restrict_content_org_wide_search":                   schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM RestrictContentOrgWideSearch property."},
			"restricted_access_control":                          schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM RestrictedAccessControl property."},
			"restricted_access_control_groups":                   schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the CSOM RestrictedAccessControlGroups property."},
			"restricted_content_discoveryfor_copilot_and_agents": schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM RestrictedContentDiscoveryforCopilotAndAgents property."},
			"sandboxed_code_activation_capability":               schema.StringAttribute{Computed: true, Description: "Maps to the CSOM SandboxedCodeActivationCapability property."},
			"sensitivity_label":                                  schema.StringAttribute{Computed: true, Description: "Maps to the CSOM SensitivityLabel property."},
			"sharing_allowed_domain_list":                        schema.StringAttribute{Computed: true, Description: "Maps to the CSOM SharingAllowedDomainList property."},
			"sharing_blocked_domain_list":                        schema.StringAttribute{Computed: true, Description: "Maps to the CSOM SharingBlockedDomainList property."},
			"sharing_capability":                                 schema.StringAttribute{Computed: true, Description: "Maps to the CSOM SharingCapability property."},
			"sharing_domain_restriction_mode":                    schema.StringAttribute{Computed: true, Description: "Maps to the CSOM SharingDomainRestrictionMode property."},
			"show_people_picker_suggestions_for_guest_users":     schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ShowPeoplePickerSuggestionsForGuestUsers property."},
			"social_bar_on_site_pages_disabled":                  schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM SocialBarOnSitePagesDisabled property."},
			"title":                                              schema.StringAttribute{Computed: true, Description: "Maps to the CSOM Title property."},
		},
	}
}

func (d *siteDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *siteDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data siteModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SPO.GetSPOSite(ctx, spo.GetSPOSiteParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-Site failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("Site not found", "no Site object for identity "+identity)
		return
	}
	readSite(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
