// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &siteScriptDataSource{}
	_ datasource.DataSourceWithConfigure = &siteScriptDataSource{}
)

type siteScriptDataSource struct{ client *clients.Client }

// NewSiteScriptDataSource looks up a SiteScript object (Get-SiteScript).
func NewSiteScriptDataSource() datasource.DataSource { return &siteScriptDataSource{} }

func (d *siteScriptDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_site_script"
}

func (d *siteScriptDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing SiteScript object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":    schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"title":       schema.StringAttribute{Computed: true, Description: "The site script display name."},
			"description": schema.StringAttribute{Computed: true, Description: "The site script description."},
			"content":     schema.StringAttribute{Computed: true, Description: "The site script JSON (the actions document)."},
		},
	}
}

func (d *siteScriptDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *siteScriptDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data siteScriptModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SPO.GetSPOSiteScript(ctx, spo.GetSPOSiteScriptParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-SiteScript failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("SiteScript not found", "no SiteScript object for identity "+identity)
		return
	}
	readSiteScript(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
