// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &storageEntityResource{}
	_ resource.ResourceWithConfigure   = &storageEntityResource{}
	_ resource.ResourceWithImportState = &storageEntityResource{}
)

type storageEntityResource struct{ client *clients.Client }

// NewStorageEntityResource manages the StorageEntity object (New-StorageEntity / Get-StorageEntity / Set-StorageEntity / Remove-StorageEntity).
func NewStorageEntityResource() resource.Resource { return &storageEntityResource{} }

type storageEntityModel struct {
	ID          types.String `tfsdk:"id"`
	Identity    types.String `tfsdk:"identity"`
	Value       types.String `tfsdk:"value"`
	Description types.String `tfsdk:"description"`
	Comment     types.String `tfsdk:"comment"`
}

func (r *storageEntityResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_storage_entity"
}

func (r *storageEntityResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a SharePoint tenant storage entity / farm property bag value (Set/Get/Remove-SPOStorageEntity, CSOM). Identity is \"<site-url>|<key>\" — the site (usually the tenant app catalog) and the entity key.",
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":    schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"value":       schema.StringAttribute{Required: true, Description: "The storage entity value."},
			"description": schema.StringAttribute{Optional: true, Computed: true, Description: "The storage entity description.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"comment":     schema.StringAttribute{Optional: true, Computed: true, Description: "The storage entity comment.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *storageEntityResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *storageEntityResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan storageEntityModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := spo.NewSPOStorageEntityParams{
		Value:       plan.Value.ValueString(),
		Description: plan.Description.ValueString(),
		Comment:     plan.Comment.ValueString(),
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SPO.NewSPOStorageEntity(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-StorageEntity failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-StorageEntity returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readStorageEntity(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *storageEntityResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state storageEntityModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *storageEntityResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state storageEntityModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := spo.SetSPOStorageEntityParams{}
	sp.Identity = id
	sp.Value = plan.Value.ValueString()
	sp.Description = plan.Description.ValueString()
	sp.Comment = plan.Comment.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPOStorageEntity(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-StorageEntity failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Value":       cfg.Value,
		"Description": cfg.Description,
		"Comment":     cfg.Comment,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *storageEntityResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state storageEntityModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.RemoveSPOStorageEntity(ctx, spo.RemoveSPOStorageEntityParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-StorageEntity failed", err.Error())
		}
	}
}

func (r *storageEntityResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *storageEntityResource) identityOf(m storageEntityModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *storageEntityResource) refresh(ctx context.Context, identity string, m *storageEntityModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SPO.GetSPOStorageEntity(ctx, spo.GetSPOStorageEntityParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-StorageEntity failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readStorageEntity(ctx, obj, m)
	return true
}

func readStorageEntity(ctx context.Context, obj map[string]any, m *storageEntityModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Value = types.StringValue(getString(obj, "Value"))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.Comment = types.StringValue(getString(obj, "Comment"))
	_ = ctx
}

func (r *storageEntityResource) reconcileState(cfg, read *storageEntityModel) {
	read.Value = reconcile.KeepStr(cfg.Value, read.Value)
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.Comment = reconcile.KeepStr(cfg.Comment, read.Comment)
}
