// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &tenantDataSource{}
	_ datasource.DataSourceWithConfigure = &tenantDataSource{}
)

type tenantDataSource struct{ client *clients.Client }

// NewTenantDataSource looks up a Tenant object (Get-Tenant).
func NewTenantDataSource() datasource.DataSource { return &tenantDataSource{} }

func (d *tenantDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tenant"
}

func (d *tenantDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing Tenant object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                                 schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":                           schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"all_organization_security_group_id": schema.StringAttribute{Computed: true, Description: "Maps to the CSOM AllOrganizationSecurityGroupId property."},
			"allow_anonymous_meeting_participants_to_access_whiteboards": schema.StringAttribute{Computed: true, Description: "Maps to the CSOM AllowAnonymousMeetingParticipantsToAccessWhiteboards property."},
			"allow_apps_bypass_of_unmanaged_device_policy":               schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowAppsBypassOfUnmanagedDevicePolicy property."},
			"allow_classic_publishing_site_creation":                     schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowClassicPublishingSiteCreation property."},
			"allow_comments_text_on_email_enabled":                       schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowCommentsTextOnEmailEnabled property."},
			"allow_downloading_non_web_viewable_files":                   schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowDownloadingNonWebViewableFiles property."},
			"allow_editing": schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowEditing property."},
			"allow_everyone_except_external_users_claim_in_private_site": schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowEveryoneExceptExternalUsersClaimInPrivateSite property."},
			"allow_file_archive":                                                         schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowFileArchive property."},
			"allow_file_archive_on_new_sites_by_default":                                 schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowFileArchiveOnNewSitesByDefault property."},
			"allow_guest_user_share_to_users_not_in_site_collection":                     schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowGuestUserShareToUsersNotInSiteCollection property."},
			"allow_legacy_auth_protocols_enabled_setting":                                schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowLegacyAuthProtocolsEnabledSetting property."},
			"allow_legacy_browser_auth_protocols_enabled_setting":                        schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowLegacyBrowserAuthProtocolsEnabledSetting property."},
			"allow_override_for_block_user_info_visibility":                              schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowOverrideForBlockUserInfoVisibility property."},
			"allow_sensitivity_label_on_records":                                         schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowSensitivityLabelOnRecords property."},
			"allow_sharing_outside_restricted_access_control_groups":                     schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowSharingOutsideRestrictedAccessControlGroups property."},
			"allow_web_property_bag_update_when_deny_add_and_customize_pages_is_enabled": schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled property."},
			"anyone_link_track_users":                                                    schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AnyoneLinkTrackUsers property."},
			"app_access_information_barriers_allow_list":                                 schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the CSOM AppAccessInformationBarriersAllowList property."},
			"app_bypass_information_barriers":                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AppBypassInformationBarriers property."},
			"app_only_bypass_people_picker_policies":                                     schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM AppOnlyBypassPeoplePickerPolicies property."},
			"apply_app_enforced_restrictions_to_ad_hoc_recipients":                       schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ApplyAppEnforcedRestrictionsToAdHocRecipients property."},
			"archive_redirect_url":                                                       schema.StringAttribute{Computed: true, Description: "Maps to the CSOM ArchiveRedirectUrl property."},
			"auth_context_resilience_mode":                                               schema.StringAttribute{Computed: true, Description: "Maps to the CSOM AuthContextResilienceMode property."},
			"bcc_external_sharing_invitations":                                           schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM BccExternalSharingInvitations property."},
			"bcc_external_sharing_invitations_list":                                      schema.StringAttribute{Computed: true, Description: "Maps to the CSOM BccExternalSharingInvitationsList property."},
			"block_app_access_with_authentication_context":                               schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM BlockAppAccessWithAuthenticationContext property."},
			"block_download_links_file_type":                                             schema.StringAttribute{Computed: true, Description: "Maps to the CSOM BlockDownloadLinksFileType property."},
			"block_send_label_mismatch_email":                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM BlockSendLabelMismatchEmail property."},
			"block_user_info_visibility":                                                 schema.StringAttribute{Computed: true, Description: "Maps to the CSOM BlockUserInfoVisibility property."},
			"block_user_info_visibility_in_one_drive":                                    schema.StringAttribute{Computed: true, Description: "Maps to the CSOM BlockUserInfoVisibilityInOneDrive property."},
			"block_user_info_visibility_in_share_point":                                  schema.StringAttribute{Computed: true, Description: "Maps to the CSOM BlockUserInfoVisibilityInSharePoint property."},
			"business_connectivity_service_disabled":                                     schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM BusinessConnectivityServiceDisabled property."},
			"comments_on_files_disabled":                                                 schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM CommentsOnFilesDisabled property."},
			"comments_on_list_items_disabled":                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM CommentsOnListItemsDisabled property."},
			"comments_on_site_pages_disabled":                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM CommentsOnSitePagesDisabled property."},
			"conditional_access_policy":                                                  schema.StringAttribute{Computed: true, Description: "Maps to the CSOM ConditionalAccessPolicy property."},
			"conditional_access_policy_error_help_link":                                  schema.StringAttribute{Computed: true, Description: "Maps to the CSOM ConditionalAccessPolicyErrorHelpLink property."},
			"content_security_policy_enforcement":                                        schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ContentSecurityPolicyEnforcement property."},
			"content_type_sync_site_templates_list":                                      schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the CSOM ContentTypeSyncSiteTemplatesList property. Allowed values: MySites."},
			"core_block_guests_as_site_admin":                                            schema.StringAttribute{Computed: true, Description: "Maps to the CSOM CoreBlockGuestsAsSiteAdmin property."},
			"core_default_link_to_existing_access":                                       schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM CoreDefaultLinkToExistingAccess property."},
			"core_default_share_link_role":                                               schema.StringAttribute{Computed: true, Description: "Maps to the CSOM CoreDefaultShareLinkRole property."},
			"core_default_share_link_scope":                                              schema.StringAttribute{Computed: true, Description: "Maps to the CSOM CoreDefaultShareLinkScope property."},
			"core_loop_default_sharing_link_role":                                        schema.StringAttribute{Computed: true, Description: "Maps to the CSOM CoreLoopDefaultSharingLinkRole property."},
			"core_loop_default_sharing_link_scope":                                       schema.StringAttribute{Computed: true, Description: "Maps to the CSOM CoreLoopDefaultSharingLinkScope property."},
			"core_organization_sharing_link_max_expiration_in_days":                      schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM CoreOrganizationSharingLinkMaxExpirationInDays property."},
			"core_organization_sharing_link_recommended_expiration_in_days":              schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM CoreOrganizationSharingLinkRecommendedExpirationInDays property."},
			"core_request_files_link_enabled":                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM CoreRequestFilesLinkEnabled property."},
			"core_request_files_link_expiration_in_days":                                 schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM CoreRequestFilesLinkExpirationInDays property."},
			"core_sharing_capability":                                                    schema.StringAttribute{Computed: true, Description: "Maps to the CSOM CoreSharingCapability property."},
			"customized_external_sharing_service_url":                                    schema.StringAttribute{Computed: true, Description: "Maps to the CSOM CustomizedExternalSharingServiceUrl property."},
			"default_link_permission":                                                    schema.StringAttribute{Computed: true, Description: "Maps to the CSOM DefaultLinkPermission property."},
			"default_sharing_link_type":                                                  schema.StringAttribute{Computed: true, Description: "Maps to the CSOM DefaultSharingLinkType property."},
			"delay_content_security_policy_enforcement":                                  schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DelayContentSecurityPolicyEnforcement property."},
			"delay_deny_add_and_customize_pages_enforcement_on_classic_publishing_sites": schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DelayDenyAddAndCustomizePagesEnforcementOnClassicPublishingSites property."},
			"disable_back_to_classic":                                                    schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DisableBackToClassic property."},
			"disable_custom_app_authentication":                                          schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DisableCustomAppAuthentication property."},
			"disable_document_library_default_labeling":                                  schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DisableDocumentLibraryDefaultLabeling property."},
			"disable_outlook_pst_version_trimming":                                       schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DisableOutlookPSTVersionTrimming property."},
			"disable_personal_list_creation":                                             schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DisablePersonalListCreation property."},
			"disable_share_point_store_access":                                           schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DisableSharePointStoreAccess property."},
			"disable_spaces_activation":                                                  schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DisableSpacesActivation property."},
			"disable_spfx_top_bottom_placeholders_in_elevated_content":                   schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DisableSpfxTopBottomPlaceholdersInElevatedContent property."},
			"disable_teams_meeting_recording_deleted_notification":                       schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DisableTeamsMeetingRecordingDeletedNotification property."},
			"disable_viva_connections_analytics":                                         schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DisableVivaConnectionsAnalytics property."},
			"disabled_adaptive_card_extension_ids":                                       schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the CSOM DisabledAdaptiveCardExtensionIds property."},
			"disabled_web_part_ids":                                                      schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the CSOM DisabledWebPartIds property."},
			"disallow_infected_file_download":                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DisallowInfectedFileDownload property."},
			"display_start_a_site_option":                                                schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM DisplayStartASiteOption property."},
			"email_attestation_re_auth_days":                                             schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM EmailAttestationReAuthDays property."},
			"email_attestation_required":                                                 schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EmailAttestationRequired property."},
			"enable_aip_integration":                                                     schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnableAIPIntegration property."},
			"enable_agent_worker_sharing_disclaimer":                                     schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnableAgentWorkerSharingDisclaimer property."},
			"enable_auto_news_digest":                                                    schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnableAutoNewsDigest property."},
			"enable_azure_adb2_b_integration":                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnableAzureADB2BIntegration property."},
			"enable_discoverable_by_organization_for_videos":                             schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnableDiscoverableByOrganizationForVideos property."},
			"enable_guest_sign_in_acceleration":                                          schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnableGuestSignInAcceleration property."},
			"enable_media_reactions":                                                     schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnableMediaReactions property."},
			"enable_minimum_version_requirement":                                         schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnableMinimumVersionRequirement property."},
			"enable_notifications_subscriptions":                                         schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnableNotificationsSubscriptions property."},
			"enable_promoted_file_handlers":                                              schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnablePromotedFileHandlers property."},
			"enable_restricted_access_control":                                           schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnableRestrictedAccessControl property."},
			"enable_sensitivity_label_for_one_note":                                      schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnableSensitivityLabelForOneNote property."},
			"enable_sensitivity_label_for_pdf":                                           schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnableSensitivityLabelForPDF property."},
			"enable_sensitivity_label_for_video_files":                                   schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnableSensitivityLabelForVideoFiles property."},
			"enforce_request_digest":                                                     schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM EnforceRequestDigest property."},
			"extend_permissions_to_unprotected_files":                                    schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ExtendPermissionsToUnprotectedFiles property."},
			"external_services_enabled":                                                  schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ExternalServicesEnabled property."},
			"external_user_expiration_required":                                          schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ExternalUserExpirationRequired property."},
			"external_user_expire_in_days":                                               schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM ExternalUserExpireInDays property."},
			"file_anonymous_link_type":                                                   schema.StringAttribute{Computed: true, Description: "Maps to the CSOM FileAnonymousLinkType property."},
			"file_picker_external_image_search_enabled":                                  schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM FilePickerExternalImageSearchEnabled property."},
			"file_preview_allowed_domain_list":                                           schema.StringAttribute{Computed: true, Description: "Maps to the CSOM FilePreviewAllowedDomainList property."},
			"folder_anonymous_link_type":                                                 schema.StringAttribute{Computed: true, Description: "Maps to the CSOM FolderAnonymousLinkType property."},
			"ib_implicit_group_based":                                                    schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM IBImplicitGroupBased property."},
			"ip_address_allow_list":                                                      schema.StringAttribute{Computed: true, Description: "Maps to the CSOM IPAddressAllowList property."},
			"ip_address_enforcement":                                                     schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM IPAddressEnforcement property."},
			"ip_address_wac_token_lifetime":                                              schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM IPAddressWACTokenLifetime property."},
			"include_at_a_glance_in_share_emails":                                        schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM IncludeAtAGlanceInShareEmails property."},
			"information_barriers_suspension":                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM InformationBarriersSuspension property."},
			"is_collab_meeting_notes_fluid_enabled":                                      schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM IsCollabMeetingNotesFluidEnabled property."},
			"is_data_access_in_card_designer_enabled":                                    schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM IsDataAccessInCardDesignerEnabled property."},
			"is_enable_app_auth_pop_up_enabled":                                          schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM IsEnableAppAuthPopUpEnabled property."},
			"is_file_preview_domain_restriction_enabled":                                 schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM IsFilePreviewDomainRestrictionEnabled property."},
			"is_fluid_enabled":                                                           schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM IsFluidEnabled property."},
			"is_loop_enabled":                                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM IsLoopEnabled property."},
			"is_wb_fluid_enabled":                                                        schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM IsWBFluidEnabled property."},
			"label_mismatch_email_help_link":                                             schema.StringAttribute{Computed: true, Description: "Maps to the CSOM LabelMismatchEmailHelpLink property."},
			"legacy_auth_protocols_enabled":                                              schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM LegacyAuthProtocolsEnabled property."},
			"legacy_browser_auth_protocols_enabled":                                      schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM LegacyBrowserAuthProtocolsEnabled property."},
			"limited_access_file_type":                                                   schema.StringAttribute{Computed: true, Description: "Maps to the CSOM LimitedAccessFileType property."},
			"major_version_limit":                                                        schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM MajorVersionLimit property."},
			"mark_new_files_sensitive_by_default":                                        schema.StringAttribute{Computed: true, Description: "Maps to the CSOM MarkNewFilesSensitiveByDefault property."},
			"mass_delete_notification_disabled":                                          schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM MassDeleteNotificationDisabled property."},
			"mass_delete_notification_disabled_for_odb":                                  schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM MassDeleteNotificationDisabledForODB property."},
			"mass_delete_notification_disabled_for_spo":                                  schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM MassDeleteNotificationDisabledForSPO property."},
			"media_transcription":                                                        schema.StringAttribute{Computed: true, Description: "Maps to the CSOM MediaTranscription property."},
			"media_transcription_automatic_features":                                     schema.StringAttribute{Computed: true, Description: "Maps to the CSOM MediaTranscriptionAutomaticFeatures property."},
			"no_access_redirect_url":                                                     schema.StringAttribute{Computed: true, Description: "Maps to the CSOM NoAccessRedirectUrl property."},
			"notifications_in_one_drive_for_business_enabled":                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM NotificationsInOneDriveForBusinessEnabled property."},
			"notifications_in_share_point_enabled":                                       schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM NotificationsInSharePointEnabled property."},
			"notify_owners_when_invitations_accepted":                                    schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM NotifyOwnersWhenInvitationsAccepted property."},
			"notify_owners_when_items_reshared":                                          schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM NotifyOwnersWhenItemsReshared property."},
			"odb_access_requests":                                                        schema.StringAttribute{Computed: true, Description: "Maps to the CSOM ODBAccessRequests property."},
			"odb_members_can_share":                                                      schema.StringAttribute{Computed: true, Description: "Maps to the CSOM ODBMembersCanShare property."},
			"office_client_adal_disabled":                                                schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM OfficeClientADALDisabled property."},
			"one_drive_block_guests_as_site_admin":                                       schema.StringAttribute{Computed: true, Description: "Maps to the CSOM OneDriveBlockGuestsAsSiteAdmin property."},
			"one_drive_default_link_to_existing_access":                                  schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM OneDriveDefaultLinkToExistingAccess property."},
			"one_drive_default_share_link_role":                                          schema.StringAttribute{Computed: true, Description: "Maps to the CSOM OneDriveDefaultShareLinkRole property."},
			"one_drive_default_share_link_scope":                                         schema.StringAttribute{Computed: true, Description: "Maps to the CSOM OneDriveDefaultShareLinkScope property."},
			"one_drive_for_guests_enabled":                                               schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM OneDriveForGuestsEnabled property."},
			"one_drive_loop_default_sharing_link_role":                                   schema.StringAttribute{Computed: true, Description: "Maps to the CSOM OneDriveLoopDefaultSharingLinkRole property."},
			"one_drive_loop_default_sharing_link_scope":                                  schema.StringAttribute{Computed: true, Description: "Maps to the CSOM OneDriveLoopDefaultSharingLinkScope property."},
			"one_drive_organization_sharing_link_max_expiration_in_days":                 schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM OneDriveOrganizationSharingLinkMaxExpirationInDays property."},
			"one_drive_organization_sharing_link_recommended_expiration_in_days":         schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM OneDriveOrganizationSharingLinkRecommendedExpirationInDays property."},
			"one_drive_request_files_link_enabled":                                       schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM OneDriveRequestFilesLinkEnabled property."},
			"one_drive_request_files_link_expiration_in_days":                            schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM OneDriveRequestFilesLinkExpirationInDays property."},
			"one_drive_storage_quota":                                                    schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM OneDriveStorageQuota property."},
			"orphaned_personal_sites_retention_period":                                   schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM OrphanedPersonalSitesRetentionPeriod property."},
			"owner_anonymous_notification":                                               schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM OwnerAnonymousNotification property."},
			"permissive_browser_file_handling_override":                                  schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM PermissiveBrowserFileHandlingOverride property."},
			"prevent_external_users_from_resharing":                                      schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM PreventExternalUsersFromResharing property."},
			"provision_shared_with_everyone_folder":                                      schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ProvisionSharedWithEveryoneFolder property."},
			"public_cdn_allowed_file_types":                                              schema.StringAttribute{Computed: true, Description: "Maps to the CSOM PublicCdnAllowedFileTypes property."},
			"public_cdn_enabled":                                                         schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM PublicCdnEnabled property."},
			"recycle_bin_retention_period":                                               schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM RecycleBinRetentionPeriod property."},
			"reduce_temp_token_lifetime_enabled":                                         schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ReduceTempTokenLifetimeEnabled property."},
			"reduce_temp_token_lifetime_value":                                           schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM ReduceTempTokenLifetimeValue property."},
			"require_accepting_account_match_invited_account":                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM RequireAcceptingAccountMatchInvitedAccount property."},
			"require_anonymous_links_expire_in_days":                                     schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM RequireAnonymousLinksExpireInDays property."},
			"restrict_external_sharing":                                                  schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the CSOM RestrictExternalSharing property."},
			"restrict_external_sharing_for_agents":                                       schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM RestrictExternalSharingForAgents property."},
			"restrict_resource_account_access":                                           schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM RestrictResourceAccountAccess property."},
			"restricted_access_control_for_one_drive_error_help_link":                    schema.StringAttribute{Computed: true, Description: "Maps to the CSOM RestrictedAccessControlForOneDriveErrorHelpLink property."},
			"restricted_access_controlfor_sites_error_help_link":                         schema.StringAttribute{Computed: true, Description: "Maps to the CSOM RestrictedAccessControlforSitesErrorHelpLink property."},
			"search_resolve_exact_email_or_upn":                                          schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM SearchResolveExactEmailOrUPN property."},
			"self_service_site_creation_disabled":                                        schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM SelfServiceSiteCreationDisabled property."},
			"sharing_allowed_domain_list":                                                schema.StringAttribute{Computed: true, Description: "Maps to the CSOM SharingAllowedDomainList property."},
			"sharing_blocked_domain_list":                                                schema.StringAttribute{Computed: true, Description: "Maps to the CSOM SharingBlockedDomainList property."},
			"sharing_capability":                                                         schema.StringAttribute{Computed: true, Description: "Maps to the CSOM SharingCapability property."},
			"sharing_domain_restriction_mode":                                            schema.StringAttribute{Computed: true, Description: "Maps to the CSOM SharingDomainRestrictionMode property."},
			"show_all_users_claim":                                                       schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ShowAllUsersClaim property."},
			"show_everyone_claim":                                                        schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ShowEveryoneClaim property."},
			"show_everyone_except_external_users_claim":                                  schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ShowEveryoneExceptExternalUsersClaim property."},
			"show_open_in_desktop_option_for_synced_files":                               schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ShowOpenInDesktopOptionForSyncedFiles property."},
			"show_people_picker_group_suggestions_for_ib":                                schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ShowPeoplePickerGroupSuggestionsForIB property."},
			"show_people_picker_suggestions_for_guest_users":                             schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ShowPeoplePickerSuggestionsForGuestUsers property."},
			"sign_in_acceleration_domain":                                                schema.StringAttribute{Computed: true, Description: "Maps to the CSOM SignInAccelerationDomain property."},
			"site_owner_manage_legacy_service_principal_enabled":                         schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM SiteOwnerManageLegacyServicePrincipalEnabled property."},
			"site_owners_can_access_missing_content":                                     schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM SiteOwnersCanAccessMissingContent property."},
			"social_bar_on_site_pages_disabled":                                          schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM SocialBarOnSitePagesDisabled property."},
			"special_characters_state_in_file_folder_names":                              schema.StringAttribute{Computed: true, Description: "Maps to the CSOM SpecialCharactersStateInFileFolderNames property."},
			"start_a_site_form_url":                                                      schema.StringAttribute{Computed: true, Description: "Maps to the CSOM StartASiteFormUrl property."},
			"stop_alerts":                                                                schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM StopAlerts property."},
			"stop_new2010_workflows":                                                     schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM StopNew2010Workflows property."},
			"stop_new2013_workflows":                                                     schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM StopNew2013Workflows property."},
			"stream_launch_config":                                                       schema.Int64Attribute{Computed: true, Description: "Maps to the CSOM StreamLaunchConfig property."},
			"sync_privacy_profile_properties":                                            schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM SyncPrivacyProfileProperties property."},
			"tls_token_binding_policy_value":                                             schema.StringAttribute{Computed: true, Description: "Maps to the CSOM TlsTokenBindingPolicyValue property."},
			"use_find_people_in_people_picker":                                           schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM UseFindPeopleInPeoplePicker property."},
			"use_persistent_cookies_for_explorer_view":                                   schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM UsePersistentCookiesForExplorerView property."},
			"view_in_file_explorer_enabled":                                              schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ViewInFileExplorerEnabled property."},
			"viewers_can_comment_on_media_disabled":                                      schema.BoolAttribute{Computed: true, Description: "Maps to the CSOM ViewersCanCommentOnMediaDisabled property."},
		},
	}
}

func (d *tenantDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *tenantDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data tenantModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	get := func(ctx context.Context) (map[string]any, bool, error) {
		_ = identity
		res, gerr := d.client.SPO.GetSPOTenant(ctx, spo.GetSPOTenantParams{})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-Tenant failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("Tenant not found", "no Tenant object for identity "+identity)
		return
	}
	readTenant(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
