// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &tenantCdnResource{}
	_ resource.ResourceWithConfigure   = &tenantCdnResource{}
	_ resource.ResourceWithImportState = &tenantCdnResource{}
)

type tenantCdnResource struct{ client *clients.Client }

// NewTenantCdnResource manages the TenantCdn configuration (Get-TenantCdn / Set-TenantCdn); it adopts the existing object and is not deleted on destroy.
func NewTenantCdnResource() resource.Resource { return &tenantCdnResource{} }

type tenantCdnModel struct {
	ID       types.String `tfsdk:"id"`
	Identity types.String `tfsdk:"identity"`
	Enabled  types.Bool   `tfsdk:"enabled"`
	Origins  types.Set    `tfsdk:"origins"`
}

func (r *tenantCdnResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tenant_cdn"
}

func (r *tenantCdnResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the Office 365 CDN for a type (Public or Private): enabled state and origins (Get/Set-SPOTenantCdnEnabled + Add/Remove-SPOTenantCdnOrigin, CSOM). Keyed by cdn type; adopts the existing config and is not disabled on destroy.",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity": schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"enabled":  schema.BoolAttribute{Required: true, Description: "Whether the CDN of this type is enabled."},
			"origins":  schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "CDN origins (relative or absolute paths).", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *tenantCdnResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *tenantCdnResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan tenantCdnModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := spo.SetSPOTenantCdnParams{}
	sp.Identity = plan.Identity.ValueString()
	sp.Enabled = plan.Enabled.ValueBool()
	sp.Origins = toStringSlice(ctx, plan.Origins, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPOTenantCdn(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-TenantCdn failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *tenantCdnResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state tenantCdnModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *tenantCdnResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state tenantCdnModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := spo.SetSPOTenantCdnParams{}
	sp.Identity = id
	sp.Enabled = plan.Enabled.ValueBool()
	sp.Origins = toStringSlice(ctx, plan.Origins, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPOTenantCdn(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-TenantCdn failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *tenantCdnResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("TenantCdn configuration not deleted", "This resource manages an existing TenantCdn configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *tenantCdnResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *tenantCdnResource) identityOf(m tenantCdnModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *tenantCdnResource) refresh(ctx context.Context, identity string, m *tenantCdnModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SPO.GetSPOTenantCdn(ctx, spo.GetSPOTenantCdnParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-TenantCdn failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readTenantCdn(ctx, obj, m)
	return true
}

func readTenantCdn(ctx context.Context, obj map[string]any, m *tenantCdnModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Enabled = types.BoolValue(getBool(obj, "Enabled"))
	m.Origins = stringSetValue(ctx, getStringSlice(obj, "Origins"))
	_ = ctx
}

func (r *tenantCdnResource) reconcileState(cfg, read *tenantCdnModel) {
	read.Enabled = reconcile.KeepBool(cfg.Enabled, read.Enabled)
	read.Origins = reconcile.KeepSet(cfg.Origins, read.Origins)
}
