// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &tenantCdnDataSource{}
	_ datasource.DataSourceWithConfigure = &tenantCdnDataSource{}
)

type tenantCdnDataSource struct{ client *clients.Client }

// NewTenantCdnDataSource looks up a TenantCdn object (Get-TenantCdn).
func NewTenantCdnDataSource() datasource.DataSource { return &tenantCdnDataSource{} }

func (d *tenantCdnDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tenant_cdn"
}

func (d *tenantCdnDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing TenantCdn object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity": schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"enabled":  schema.BoolAttribute{Computed: true, Description: "Whether the CDN of this type is enabled."},
			"origins":  schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "CDN origins (relative or absolute paths)."},
		},
	}
}

func (d *tenantCdnDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *tenantCdnDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data tenantCdnModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SPO.GetSPOTenantCdn(ctx, spo.GetSPOTenantCdnParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-TenantCdn failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("TenantCdn not found", "no TenantCdn object for identity "+identity)
		return
	}
	readTenantCdn(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
