// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &themeDataSource{}
	_ datasource.DataSourceWithConfigure = &themeDataSource{}
)

type themeDataSource struct{ client *clients.Client }

// NewThemeDataSource looks up a Theme object (Get-Theme).
func NewThemeDataSource() datasource.DataSource { return &themeDataSource{} }

func (d *themeDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_theme"
}

func (d *themeDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing Theme object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":    schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"theme_json":  schema.StringAttribute{Computed: true, Description: "The theme palette as a JSON string (e.g. {\"palette\":{\"themePrimary\":\"#0078d4\"}})."},
			"is_inverted": schema.BoolAttribute{Computed: true, Description: "Whether the theme is a dark (inverted) theme."},
		},
	}
}

func (d *themeDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *themeDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data themeModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SPO.GetSPOTheme(ctx, spo.GetSPOThemeParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-Theme failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("Theme not found", "no Theme object for identity "+identity)
		return
	}
	readTheme(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
