// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/go-spo/spo"
	"github.com/terraprovider/terraform-provider-spo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &themeResource{}
	_ resource.ResourceWithConfigure   = &themeResource{}
	_ resource.ResourceWithImportState = &themeResource{}
)

type themeResource struct{ client *clients.Client }

// NewThemeResource manages the Theme object (New-Theme / Get-Theme / Set-Theme / Remove-Theme).
func NewThemeResource() resource.Resource { return &themeResource{} }

type themeModel struct {
	ID         types.String `tfsdk:"id"`
	Identity   types.String `tfsdk:"identity"`
	ThemeJson  types.String `tfsdk:"theme_json"`
	IsInverted types.Bool   `tfsdk:"is_inverted"`
}

func (r *themeResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_theme"
}

func (r *themeResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a SharePoint tenant theme (Add/Get/Set/Remove-SPOTheme, CSOM), keyed by the theme name.",
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":    schema.StringAttribute{Required: true, Description: "Name (Identity) of the object; also the create key. Changing it forces replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"theme_json":  schema.StringAttribute{Required: true, Description: "The theme palette as a JSON string (e.g. {\"palette\":{\"themePrimary\":\"#0078d4\"}})."},
			"is_inverted": schema.BoolAttribute{Optional: true, Computed: true, Description: "Whether the theme is a dark (inverted) theme.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *themeResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *themeResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan themeModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := spo.NewSPOThemeParams{
		ThemeJson: plan.ThemeJson.ValueString(),
	}
	p.Identity = plan.Identity.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SPO.NewSPOTheme(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-Theme failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := plan.Identity.ValueString()
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-Theme returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readTheme(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *themeResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state themeModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *themeResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state themeModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := spo.SetSPOThemeParams{}
	sp.Identity = id
	sp.ThemeJson = plan.ThemeJson.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.SetSPOTheme(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-Theme failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Palette": cfg.ThemeJson,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *themeResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state themeModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SPO.RemoveSPOTheme(ctx, spo.RemoveSPOThemeParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-Theme failed", err.Error())
		}
	}
}

func (r *themeResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *themeResource) identityOf(m themeModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *themeResource) refresh(ctx context.Context, identity string, m *themeModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SPO.GetSPOTheme(ctx, spo.GetSPOThemeParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-Theme failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readTheme(ctx, obj, m)
	return true
}

func readTheme(ctx context.Context, obj map[string]any, m *themeModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.IsInverted = types.BoolValue(getBool(obj, "IsInverted"))
	_ = ctx
}

func (r *themeResource) reconcileState(cfg, read *themeModel) {
	read.ThemeJson = reconcile.KeepStr(cfg.ThemeJson, read.ThemeJson)
	read.IsInverted = reconcile.KeepBool(cfg.IsInverted, read.IsInverted)
}
