// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

// generatedResources lists every generated resource constructor.
func generatedResources() []func() resource.Resource {
	return []func() resource.Resource{
		NewBlockedPageContentTypeResource,
		NewHomeSiteResource,
		NewHubSiteResource,
		NewKnowledgeHubSiteResource,
		NewListDesignResource,
		NewOrgAssetsLibraryResource,
		NewOrgNewsSiteResource,
		NewRestrictedSearchResource,
		NewSiteResource,
		NewSiteDesignResource,
		NewSiteDesignRightsResource,
		NewSiteScriptResource,
		NewStorageEntityResource,
		NewTenantResource,
		NewTenantCdnResource,
		NewThemeResource,
	}
}

// generatedDataSources lists every generated data source constructor.
func generatedDataSources() []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewBlockedPageContentTypeDataSource,
		NewHomeSiteDataSource,
		NewHubSiteDataSource,
		NewKnowledgeHubSiteDataSource,
		NewListDesignDataSource,
		NewOrgAssetsLibraryDataSource,
		NewOrgNewsSiteDataSource,
		NewRestrictedSearchDataSource,
		NewSiteDataSource,
		NewSiteDesignDataSource,
		NewSiteDesignRightsDataSource,
		NewSiteScriptDataSource,
		NewStorageEntityDataSource,
		NewTenantDataSource,
		NewTenantCdnDataSource,
		NewThemeDataSource,
	}
}
